### ISSUE TITLE
sftp_server as arbitrary callable regressed in 1.16.1

### ISSUE THREAD

**Issue by oremanj** [ronf/asyncssh#213] opened 2019-05-23 02:05 UTC
This commit: https://github.com/ronf/asyncssh/commit/36d6def316fa6e760a8cfec11a6b939f8b358088 (new in 1.16.1) effectively adds a requirement that the `sftp_factory` (as passed to `asyncssh.create_server()` or `asyncssh.listen()`) be a type that subclasses `SFTPServer`, even though it continues to be documented as accepting any callable that returns an `SFTPServer`. This broke code I had written that passed `sftp_factory=partial(SFTPServer, chroot="something")`. Could you either restore the ability to use an arbitrary callable (maybe by setting the new attributes on the returned object instead of making them exist already when `__init__` is called), or document the backwards-incompatible change?

I was a bit surprised to see this show up in a patch release (1.16.0 to 1.16.1), since I had assumed from the three-part version number that AsyncSSH used semantic versioning. I checked the docs and found no mention of a versioning policy, so I guess I assumed incorrectly. Could you clarify what your intentions are regarding how users should interpret different sorts of version number increases?

**Comment by ronf** [comment] 2019-05-25 04:20
My apologies - this change was definitely not intended to introduce an incompatible change. In fact, the whole reason why the new code is doing the rather unusual thing of calling __new__ and __init__ explicitly was in an attempt to remain backward compatible with the original function arguments of "conn" and "chroot" in the __init__ call for subclasses of SFTPServer, even though the parent SFTPServer class really needs the channel object passed to it, not the connection object. I actually had forgotten that the sftp_factory argument was documented as supporting an arbitrary callable that returned an SFTPFactory object.

While I can make it set the the channel after calling the sftp_factory callable, the downside to this would be that the __init__ call of the returned object would no longer have the ability to query channel state like the environment variables set on the channel. I'm not sure there's any way to allow the channel information to be available in __init__ and still provide backward compatibility in the callable case. So, I'd like to offer the following suggestion:

I can check if the sftp_factory is a class or something else. When it is a class, I set the channel information before calling __init__ as is done in 36d6def. However, if it is some other callable, I set the channel information on the returned object after it is constructed. This would mean you couldn't access information like the environment variables until after the SFTP channel is fully created, but the ability to pass in a callable instead of a class would be restored.

What do you think?

On your question about semantic versioning, I must admit I haven't been following that strictly. I do follow the numbering, and I do intend to limit backwards-incompatible changes to only being introduced in major versions (after release 1.0.0). However, I have on occasion introduced minor enhancements which are intended to be backward-compatible in patch releases rather than always incrementing the minor version. Significant enhancements are generally done as minor versions, but I don't always keep patch releases to being purely bug fixes. As an example, I have added support for new ciphers in patch releases.

**Comment by ronf** [comment] 2019-05-25 21:09
A fix for this is now available in the "develop" branch as commit 7e8683c. Sorry for the regression! This will get rolled into the next release.

**Comment by ronf** [comment] 2019-06-01 05:17
This fix is now available in release 1.17.0.

**Closed by ronf** 2019-06-01 05:17 UTC
