### ISSUE TITLE
Unable to get exit status

### ISSUE THREAD

**Issue by redixin** [ronf/asyncssh#28] opened 2015-10-07 18:43 UTC
I tried modified sample from docs:

```python
    import asyncio, asyncssh, sys

    class MySSHClientSession(asyncssh.SSHClientSession):
        def data_received(self, data, datatype):
            if datatype == asyncssh.EXTENDED_DATA_STDERR:
                print(data, end='', file=sys.stderr)
            else:
                print(data, end='')
        def exit_status_received(self, status):
            if status:
                print('Program exited with status %d' % status, file=sys.stderr)
            else:
                print('Program exited successfully')
        def connection_lost(self, exc):
            if exc:
                print('SSH session error: ' + str(exc), file=sys.stderr)

    @asyncio.coroutine
    def run_client():
        with (yield from asyncssh.connect('192.168.1.1', username="root", client_keys=["/home/eye/.ssh/test"])) as conn:
            chan, session = yield from conn.create_session(MySSHClientSession, 'ls abc')
            yield from chan.wait_closed()

    try:
        asyncio.get_event_loop().run_until_complete(run_client())
    except (OSError, asyncssh.Error) as exc:
        sys.exit('SSH connection failed: ' + str(exc))
```

and got:

```
$ python /tmp/d.py 
ls: abc: No such file or directory
$
```
Seems `exit_status_received` was not called at all.

**Comment by ronf** [comment] 2015-10-08 02:45
I'm not able to reproduce this here. What kind of SSH server are you connecting to?

One thing to realize here is that exit_status_received() will only be called if the server actually returns an exit status, and not all of them do. It's possible for a server to send a channel close without ever providing either an exit status or an exit signal.

**Comment by redixin** [comment] 2015-10-08 11:52
I tried openssh and dropbear:

 - SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3
 - Dropbear server v2015.67

Both returns exit status (at least openssh client is able to retrieve it):

```
$ ssh root@192.168.1.1 exit 42
$ echo $?
42
$ ssh localhost ls abc
ls: cannot access abc: No such file or directory
$ echo $?
2
$
```

More details about environment:
```
Python 3.4.0
asyncssh==1.2.1
pycrypto==2.6.1
wheel==0.24.0
```

**Comment by ronf** [comment] 2015-10-08 13:06
Ok - I've been able to reproduce this now, but for some reason I only see it when connecting to a Linux SSH server and not a MacOS SSH server, even when both of them are the same version of OpenSSH. This is consistent regardless of whether my AsyncSSH client code is running on MacOS or Linux.

The issue has to do with the order of the messages being received from the server. In the case where the problem occurs, the order of the messages coming from the server is an EOF on the channel first, followed by a request to deliver the exit status, and then a close. In the case of OpenSSH running on MacOS, I consistently see the request to deliver the exit status first, then the EOF on the channel, and finally the close.

AsyncSSH is capable of dealing with either message order, but there's a subtle interaction going on here due to the two different ways EOF can be handled. AsyncSSH follows the asyncio paradigm for delivering EOF described at https://docs.python.org/3/library/asyncio-protocol.html#streaming-protocols:

```
Protocol.eof_received()
    Called when the other end signals it won’t send any more data (for example by calling
    write_eof(), if the other end also uses asyncio).

    This method may return a false value (including None), in which case the transport
    will close itself. Conversely, if this method returns a true value, closing the transport
    is up to the protocol. Since the default implementation returns None, it implicitly
    closes the connection.
```

So, by default the transport is automatically closed as soon as EOF is received, and that prevents any other callbacks from being delivered, including the exit status.

A workaround for this is to define your own eof_received() callback in your SSHClientSession class which returns True. That will prevent AsyncSSH from automatically closing the transport on EOF, but will still automatically close it when it later receives the close channel message from the server (at which time the wait_closed() call will return and the application will exit).

I'd prefer not to change the behavior around automatically triggering the close if eof_received() returns a false value, as that's what Python's asyncio has defined. However, I would also like to preserve the rule that once close() is called on a channel, no further callbacks will be delivered to the associated session. That way, an application calling close() explicitly can be sure that their client session object can clean itself up and not have to worry about being called again afterward. Unfortunately, these two behaviors together lead to this problem.

**Comment by redixin** [comment] 2015-10-08 17:02
It works for me with workaround:
```python
class MySSHClientSession(asyncssh.SSHClientSession):
  def eof_received(self):
    return True
```

Thanks a lot.

**Comment by ronf** [comment] 2015-10-10 16:23
I thought about this a bit more and realized that I can match the semantics expected by asyncio's eof_received() callback if I simply send an EOF back to the peer if one has not already been sent when one is received and the eof_received() call on the session returns False. This avoids the channel remaining half-open while still leaving the potential to send or receive exit status and exit signal notifications.

With this change, the workaround above should no longer be necessary. The change is now checked into both the master & develop branches if you'd like to try it. I'll try to get a new release up on PyPI with this fix soon. Thanks @redixin for reporting the problem!

**Closed** 2015-10-30 04:43 UTC
Labels: bug

**Comment by RobertDeRose** [comment] 2025-03-07 08:53
@ronf I know this is a very old issue, but I am actually experiencing this behavior when connecting from macOS to Ubuntu 20.04.



Here is the code I am using:

```python

async def retry_connect(*args, max_retries=3, initial_delay=1, **kwargs) -> asyncssh.SSHClientConnection | None:
    for attempt in range(1, max_retries):
        try:
            return await asyncssh.connect(*args, **kwargs)
        except Exception as e:
            logger.warning(f"Connection attempt {attempt + 1} of {max_retries} failed: {e}")
            if attempt < max_retries:
                delay = initial_delay * (2**attempt)
                logger.warning(f"Retrying in {delay:.2f} seconds")
                await asyncio.sleep(delay)
            else:
                raise

async def _readlines(pipe: asyncssh.SSHReader, log: Callable):
    while not pipe.at_eof():
        try:
            line = await asyncio.wait_for(pipe.readline(), timeout=1.0)
            if line and not ("password for" in line or PASSWORD in line):
                log(line)
        except asyncio.TimeoutError:
            pass

async def readlines(process: asyncssh.SSHClientProcess, output_view: ft.TextField):
    log = partial(get_logger(output_view), leader="[SHELL]")
    await _readlines(process.stdout, log)

    log = partial(get_logger(output_view), is_error=True)
    await _readlines(process.stderr, log)

        async with await retry_connect(
            HOST,
            username=USERNAME,
            password=PASSWORD,
            known_hosts=None,
            term_type="xterm-color",
            options=asyncssh.SSHClientConnectionOptions(keepalive_interval=5),
        ) as conn:
            if conn is None:
                log("Failed to connect to device", is_error=True)
                logger.error("Failed to connect to %s to run command %s", HOST, command)
                return

            async with conn.create_process(command, input=input) as process:
                await readlines(process, output_view)
                return process.returncode

```

The process.returncode will randomly, so it seems, return None, and this inconsistency makes it really hard to know if the command completed or not.

If you have any suggestions for improving this code or a work-around it would be greatly appreciated
