### ISSUE TITLE
Not able to connect to Ericsson Device using asyncssh

### ISSUE THREAD

**Issue by khurramsaleembutt** [ronf/asyncssh#299] opened 2020-08-03 22:31 UTC
I am trying to connect to Ericsson device using scrapli which is using asyncssh as a transport method but i am failing to pull the data back and need your advise and support for this!

Below is debug output for the failed node....
[async_fail_debug(3).txt](https://github.com/ronf/asyncssh/files/5019084/async_fail_debug.3.txt)

Below is the code attached!

[async_code.txt](https://github.com/ronf/asyncssh/files/5019106/async_code.txt)

Please support to check the below issue!

**Comment by carlmontanari** [comment] 2020-08-03 22:48
Hey @ronf !

I checked into this as best I could as well... the closest thing I was able to find was #257 , however from logs from this device connecting with not asyncssh (using scrapli with a different transport "plugin" -- basically /bin/ssh directly w/ a subprocess wrapper more or less), the connection works as expected. There didn't appear to be any big banner or any other issue that would cause scrapli/asyncssh to be upset. 

Here is the output from @khurramsaleembutt testing w/ the other scrapli transport (sync stuff):

```
INFO:scrapli.transport-10.197.17.244:Attempting to open session with the following command: ['ssh', '10.197.17.244', '-p', '22', '-o', 'ConnectTimeout=5', '-o', 'ServerAliveInterval=10', '-l', 'cli', '-o', 'Stri
ctHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-F', '/dev/null']
DEBUG:scrapli.transport-10.197.17.244:Session to host 10.197.17.244 spawned
DEBUG:scrapli.transport-10.197.17.244:Attempting to authenticate. Read: b"Warning: Permanently added '10.197.17.244' (ECDSA) to the list of known hosts.\r\r\n"
DEBUG:scrapli.transport-10.197.17.244:Attempting to authenticate. Read: b'------------------------------------------\r\n  MINI-LINK 6600  Command Line Interface\r\n------------------------------------------\r\n\
r\n'
DEBUG:scrapli.transport-10.197.17.244:Attempting to authenticate. Read: b'Welcome to WR-2002-TN01\r\n'
DEBUG:scrapli.transport-10.197.17.244:Attempting to authenticate. Read: b'Password: '
INFO:scrapli.transport-10.197.17.244:Found password prompt, sending password
DEBUG:scrapli.transport-10.197.17.244:Attempting to determine if authentication was successful
DEBUG:scrapli.transport-10.197.17.244:Attempting to validate authentication. Read: b'********\r\n'
DEBUG:scrapli.transport-10.197.17.244:Cannot determine if authenticated,
        Read: b'********\n'
DEBUG:scrapli.transport-10.197.17.244:Attempting to validate authentication. Read: b'\r\r\nWR-2002-TN01>\r\r\nWR-2002-TN01>'
DEBUG:scrapli.transport-10.197.17.244:Authenticated to host 10.197.17.244 with password
INFO:scrapli.transport-10.197.17.244:Successfully authenticated to 10.197.17.244
INFO:scrapli.driver-10.197.17.244:Connection to 10.197.17.244 opened successfully
INFO:scrapli.channel-10.197.17.244:Attempting to send input: show version; strip_prompt: True
DEBUG:scrapli.channel-10.197.17.244:Write: 'show version'
DEBUG:scrapli.channel-10.197.17.244:Read: b'show version'
INFO:scrapli.channel-10.197.17.244:Read: b'show version'
DEBUG:scrapli.channel-10.197.17.244:Write (sending return character): '\n'
DEBUG:scrapli.channel-10.197.17.244:Read: b'\n'
DEBUG:scrapli.channel-10.197.17.244:Read: b'Active SBL          : CXP: 9036600/1 MINI-LINK 6600 6366 1.12 R13T107\nPassive SBL         : CXP: 9036600/1 MINI-LINK 6600 6366 1.7 R8M130\nNPU Passive SW      
```

I compared debug level 3 output that @khurramsaleembutt captured to a local device I have (different kind of device, I dont have access to any Ericsson stuff), and things look pretty much the same right up through `MSG_CHANNEL_OPEN`, then my device continues on as expected after seeing:

```
Z....session....
  00000010: 00 20 00 00 00 00 80 00                          . ......
```

on the channel, where the Ericsson device ends right there with the `Connection lost` message.

@khurramsaleembutt said they didn't see anything indicating that auth succeeded in the device logs, however that seems wrong since we for sure see `Auth for user cli succeeded` in the debug logs.

Not sure I can be much help on this one outside of answering scrapli-related questions, but just wanted to add some context!

Carl

**Comment by ronf** [comment] 2020-08-04 02:30
Thanks for the added input, @carlmontanari - it's much appreciated!

@khurramsaleembutt, unfortunately there's nothing out of the ordinary in the AsyncSSH logs you sent. Everything is looking good during the key exchange and the authentication, and both complete successfully. The problem seems to occur when AsyncSSH attempts to open an interactive (shell) session. The remote device never responds to the MSG_CHANNEL_OPEN, and instead it appears to close the TCP connection without sending any response back. In particular, no error is sent, so it's hard to know what went wrong. Is there any chance you have access to logs from the Ericsson device that might shed some light on what it doesn't like?

One thing I notice is that AsyncSSH is sending a MSG_IGNORE after the authentication succeeds and before the MSG_CHANNEL_OPEN. According to RFC 4253:

```
11.2.  Ignored Data Message

      byte      SSH_MSG_IGNORE
      string    data

   All implementations MUST understand (and ignore) this message at any
   time (after receiving the identification string).  No implementation
   is required to send them.  This message can be used as an additional
   protection measure against advanced traffic analysis techniques.
```

This message is supposedly allowed to appear anywhere, but I've run into a few SSH implementations out there which can have trouble if a MSG_IGNORE appears in a place where they are looking for something else. The device may be expecting _only_ a MSG_CHANNEL_OPEN after authentication succeeds and it may abort if it sees anything else.

Unfortunately, I don't have a configuration option to disable the IGNORE messages, but you might try looking for the following block of code in connection.py (around line 1169 in the latest code) and commenting it out:

```python
        # If we're encrypting and we have no data outstanding, insert an
        # ignore packet into the stream
        if self._send_encryption and pkttype not in (MSG_IGNORE, MSG_EXT_INFO):
            self.send_packet(MSG_IGNORE, String(b''))
```

Alternately, you might try changing the "if" statement there to:

```python
        if self._send_encryption and pkttype not in (MSG_IGNORE, MSG_EXT_INFO, MSG_CHANNEL_OPEN):
```

If that fixes the problem, I can look into providing a workaround of some kind for this.

**Comment by khurramsaleembutt** [comment] 2020-08-07 14:01
@ronf @carlmontanari I tried both the options(disabling 2 lines and changing the "if" statement) but no luck! Is there any way i can help you or you can help me to fix this issue?

I would be very grateful if u can find any solution to fix this issue for me if possible!

My audit log is telling that even the authentication is not complete otherwise i should have the following message

![image](https://user-images.githubusercontent.com/63533468/89653359-981ba580-d8cf-11ea-9276-39da6387671c.png)

**Comment by ronf** [comment] 2020-08-08 03:41
Unfortunately, if the MSG_IGNORE isn't the problem and there's nothing in the device's log that provides more information, I'm not sure what to suggest. Are you able to connect with OpenSSH? If so, could you turn up the verbosing on that (-vvv) and provide a log similar to the level-3 AsyncSSH log you provided? Perhaps something will jump out there as being different that we can further explore.

Based on the AsyncSSH log, the auth is definitely succeeding, and the remote device is sending MSG_USERAUTH_SUCCESS:

```
INFO:asyncssh:[conn=0] Beginning auth for user cli
DEBUG:asyncssh:[conn=0, pktid=5] Sent MSG_IGNORE (2), 5 bytes
  00000000: 02 00 00 00 00                                   .....
DEBUG:asyncssh:[conn=0, pktid=6] Sent MSG_USERAUTH_REQUEST (50), 34 bytes
  00000000: 32 00 00 00 03 63 6c 69 00 00 00 0e 73 73 68 2d  2....cli....ssh-
  00000010: 63 6f 6e 6e 65 63 74 69 6f 6e 00 00 00 04 6e 6f  connection....no
  00000020: 6e 65                                            ne
DEBUG:asyncssh:[conn=0, pktid=4] Received MSG_USERAUTH_SUCCESS (52), 1 byte
  00000000: 34                                               4
INFO:asyncssh:[conn=0] Auth for user cli succeeded
DEBUG:scrapli.transport-10.197.17.244:Authenticated to host 10.197.17.244 with password
```

After this, AsyncSSH requests an interactive (shell) session:

```
DEBUG:asyncssh:[conn=0, chan=0] Set write buffer limits: low-water=16384, high-water=65536
INFO:asyncssh:[conn=0, chan=0] Requesting new SSH session
DEBUG:asyncssh:[conn=0, chan=0]   Initial recv window 2097152, packet size 32768
DEBUG:asyncssh:[conn=0, pktid=7] Sent MSG_IGNORE (2), 5 bytes
  00000000: 02 00 00 00 00                                   .....
DEBUG:asyncssh:[conn=0, chan=0, pktid=8] Sent MSG_CHANNEL_OPEN (90), 24 bytes
  00000000: 5a 00 00 00 07 73 65 73 73 69 6f 6e 00 00 00 00  Z....session....
  00000010: 00 20 00 00 00 00 80 00                          . ......
```

Unfortunately, that's when the device closes the TCP connection, without sending any kind of error information:

```
INFO:asyncssh:[conn=0] Connection lost
INFO:asyncssh:[conn=0, chan=0] Closing channel due to connection close
INFO:asyncssh:[conn=0, chan=0] Channel closed: Connection lost
```

So, we'll need to see if there are any messaging differences between what AsyncSSH is sending and what a "working" connection looks like. Perhaps it doesn't like the values provided for window size or max packet size. You could try adjusting those to see if that made any difference. I think AsyncSSH should be using values similar to OpenSSH by default, though.

**Comment by khurramsaleembutt** [comment] 2020-08-08 11:22
Dear Mr. Ronf,

Find below detailed ssh verbose output for any clue that what is going wrong!

[Ssh_Verbose_Output.txt](https://github.com/ronf/asyncssh/files/5045165/Ssh_Verbose_Output.txt)

**Comment by ronf** [comment] 2020-08-08 14:24
Thank you. One major difference I see here is that the device doesn't seem to be requiring SSH authentication:

```
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (none).
Authenticated to 10.197.17.244 ([10.197.17.244]:22).
```

Instead, it appears to be doing the auth prompts itself after the SSH handshake completes and an interactive session is opened.

Is there some configuration on the device which is disabling auth here but not disabling it for AsyncSSH, based on the 
client IP or perhaps the SSH version string if both connections are coming from the same host?

If you set things up to require SSH password-based auth for OpenSSH, does it still succeed?

**Comment by carlmontanari** [comment] 2020-08-08 16:13
Ah this is interesting! @khurramsaleembutt can you try using the `paramiko` transport option in scrapli? I would bet that that acts in the same/similar way as asyncssh for this situation. The `system` transport probably works because it acts exactly like a user does -- sitting on a terminal, entering a password -- there is no concept of authentication from a protocol perspective (well obviously thats a bit of a lie, because key based auth, but ignore that for now :)) because its just doing what the user would do. 

@ronf is it possible to create a connection and skip the auth portion of things? Right now I have two methods of the scrapli asyncssh driver -- one for user/pass and one for key based auth -- we try key based auth first (if a key is provided) and then fallback to user/pass. These are just using the `asyncssh.connect` method with different args depending on which type of auth we are trying. Is it possible (maybe by instantiating the `SSHClientConnection` directly?) to create a connection that ignores auth? Then scrapli can just handle the user/password prompt stuff itself "in band" in the channel.

I know of at least one other platform that does this same thing (Cisco wireless controllers), so it would be good for me to handle this in scrapli! I'll try to poke around on this sometime this weekend some more!

Carl

**Comment by ronf** [comment] 2020-08-08 17:39
Hi Carl,

The decision about whether auth is required or not is up to the server. Regardless of the auth-related arguments you pass in, AsyncSSH starts by sending a USERAUTH_REQUEST with auth method of "none". If that gets back a USERAUTH_SUCCEEDED, auth is complete. If it gets back a USERAUTH_FAILED, that will come with a list of auth methods the server supports, and then AsyncSSH will choose one of those depending on a combination of what the server supports and the auth information you provided to it. Recently, I also added a "preferred_auth" argument when you connect to provide a preferred order to try the auth methods if more than one of them are supported by both the client and server.

Looking at the original AsyncSSH trace again, I actually misread it. I thought password auth was performed, but that was actually a scrapli log message, not an AsyncSSH one. It looks like the server _did_ return success on the initial auth request which sent "none", just like with OpenSSH:

```
DEBUG:asyncssh:[conn=0, pktid=6] Sent MSG_USERAUTH_REQUEST (50), 34 bytes
  00000000: 32 00 00 00 03 63 6c 69 00 00 00 0e 73 73 68 2d  2....cli....ssh-
  00000010: 63 6f 6e 6e 65 63 74 69 6f 6e 00 00 00 04 6e 6f  connection....no
  00000020: 6e 65                                            ne
DEBUG:asyncssh:[conn=0, pktid=4] Received MSG_USERAUTH_SUCCESS (52), 1 byte
  00000000: 34                                               4
INFO:asyncssh:[conn=0] Auth for user cli succeeded
```

So, that's not a difference after all. Scrapli reported the following, though:

```
DEBUG:scrapli.transport-10.197.17.244:Authenticated to host 10.197.17.244 with password
```

This shouldn't cause anything to break, but it's technically incorrect since no auth was performed. It's probably hard for you to know that, though, if you are providing client_keys and/or a password up front even before they are requested. As an aside, feel free to provide both a password and keys if you have them in a single call and AsyncSSH will figure out for you which to use (if any).

Unfortunately, we're back to square one on trying to figure out the differences.

One difference is that OpenSSH sends the "no-more-session@openssh.com" request before sending the CHANNEL_OPEN, but I would certainly hope the device wouldn't be depending on that.

The OpenSSH log doesn't show the raw packet bytes, so I can't see what window size is being sent. That shows up in the open confirm, but not in the open. It's possible there might be some difference there, but AsyncSSH is defaulting to 2 MiB, and that seems to match the receive window the device is sending back when it succeeds, so I would think that value should be ok. Also, looking at the OpenSSH sources, its default it sends seems to be 2 MiB, so I'm guessing that was the case here. Similarly, the max packet size seems to be 32 KiB in both cases.

@khurramsaleembutt, could you regenerate the AsyncSSH level 3 debug log with the fix above to turn off MSG_IGNORE, just to make sure that this is working correctly? That's the only significant difference I see other than the "no-more-sessions" request coming from OpenSSH.

**Comment by khurramsaleembutt** [comment] 2020-08-09 12:48
@carlmontanari 

Hi Brother, you are right, i m not able to pull the data back using "paramiko"

Log file below!

[scrapli.log](https://github.com/ronf/asyncssh/files/5047441/scrapli.log)

Code below!

[Transport_paramiko.txt](https://github.com/ronf/asyncssh/files/5047443/Transport_paramiko.txt)

Exception!

[Exception.txt](https://github.com/ronf/asyncssh/files/5047447/Exception.txt)

@carlmontanari Mr. Carl, As a side note to elaborate something because this may be the reason of asyncssh and paramiko not working with Ericsson device. I was using Netmiko which is using paramiko as well under the hood, i was having the same authentication failure message pasted above then as a workaround what i did, i sent a blank password in the dictionary 
remote_devices = {
                'device_type': 'autodetect',
                'host': device['ipaddr'],
                'username': 'cli',
                'password': ''}
and used the timing function available in Netmiko to send the password e.g. **net_connect.send_command_timing('ericsson' + '\n')** and then things worked for me in Netmiko but here with Scrapli, it is not even working with that kind of setup as i m new to Scrapli and have not read much about it that if there is any function available in Scrapli which is purely based on timing and not prompts to finish its job.

Just for your information if above is causing any problems with paramiko and asyncssh........

@ronf 

Below is the snippet after commenting out 2 lines!

![image](https://user-images.githubusercontent.com/63533468/89731885-5f0c3e00-da53-11ea-9d77-9d5b7868e8eb.png)

log file after commenting out 2 lines and restarting WSL(Windows Subsystem for linux)!

[log file.txt](https://github.com/ronf/asyncssh/files/5047485/log.file.txt)

At the end, thanks very much once again for the efforts you are making to fix this issue!

**Comment by carlmontanari** [comment] 2020-08-09 15:51
@khurramsaleembutt can you put an empty string for a password (try w/ asyncssh transport and maybe even paramiko for kicks) and then check out the logs to see if it gets further along. if it does and you need to do like w/ netmiko, you can do it with an `on_open` function that is basically a callable passed to the scrapli constructor - readme section [here](https://github.com/carlmontanari/scrapli#on-open) -- alternatively you can just send the password directly like: `conn.transport.write('ericson\n')` (note the newline same as with netmiko). If you wanted to get fancier you can read from the channel until you see a password prompt and all that, but for testing this (+logging) may be good enough to get things further along.

Sorry @ronf for hi-jacking this issue!

**Comment by ronf** [comment] 2020-08-10 02:05
No problem at all - thanks for the continued help here, @carlmontanari.

Regarding the MSG_IGNORE change, thanks for sending the log @khurramsaleembutt - I can confirm that the change did what it was supposed to. It looks like that isn't the problem here, though, since it behaved the same before and after.

**Comment by ronf** [comment] 2021-09-06 21:38
Closing due to inactivity. Please open a new issue if you have additional questions.

**Closed by ronf** 2021-09-06 21:38 UTC
