### ISSUE TITLE
Instant 'SSH connection closed' when connecting to windows SSH server

### ISSUE THREAD

**Issue by prolitornandbasturtrumerthydempe** [ronf/asyncssh#348] opened 2021-02-23 16:23 UTC
I'm using the tutorial code from python's [chess module](https://python-chess.readthedocs.io/en/latest/engine.html#asyncssh)

I connect to the SSH server but then it immediately disconnects on the same second that it connects.

`windows_server` is the name of my Windows SSH server that I'm trying to connect to, named in `config`. The SSH server is running [Bitwise Tunnelier](https://www.bitvise.com/ssh-server).

**My code:**

```
import asyncio
import asyncssh
import chess
import chess.engine


stockfish_path = "R:\dl2\stockfish_13_win_x64_modern\stockfish_13_win_x64_modern.exe"

async def main() -> None:
    async with asyncssh.connect("windows_server") as conn:
        channel, engine = await conn.create_subprocess(chess.engine.UciProtocol, stockfish_path)
        await engine.initialize()

        # Play, analyse, ...
        await engine.ping()

asyncio.run(main())
```

Can you help me troubleshoot? I'm not sure what the problem is

**Comment by ronf** [comment] 2021-02-23 16:37
As spam as you exit out of the "async with asyncssh.connect()" block, the connection will automatically be closed. If the initialize() and ping() operations return quickly, closing the connection in the same second would be expected behavior. If you add something like "await asyncio.sleep(5)" after the ping() call, does that keep the connection open for longer, or does it still close immediately?

Have you tried enabling debug logging? That would look something like:

```python
import logging
logging.basicConfig()
asyncssh.set_log_level('DEBUG')
asyncssh.set_debug_level(2)
```

If so, does that show anything interesting? Also, have you checked the logs on the server side?

You mention using tunneling with the Bitvise SSH server on Windows, but the create_subprocess() call would try to actually execute the stockfish process on the Windows server with stdin/stdout connected to the AsyncSSH subprocess. I'm guessing that's what you want here, but just wanted to double check since you mentioned tunneling.

**Comment by ronf** [comment] 2021-09-06 21:34
Closing due to inactivity. Please open a new issue if you have additional questions.

**Closed by ronf** 2021-09-06 21:34 UTC
