### ISSUE TITLE
Certificate auth broken on connecting to OpenSSH servers older than v8.8

### ISSUE THREAD

**Issue by kawmarco** [ronf/asyncssh#570] opened 2023-06-01 18:00 UTC
Hi @ronf, this is a follow up on #517 (BTW thanks so much for following up on it so quickly).

The fix implemented for that issue works on connecting with devices running newer versions of OpenSSH (newer than v8.8? https://ikarus.sg/rsa-is-not-dead/) but it broke when trying to use certificate auth in older versions (e.g. 7.5, 8.2) as it expects the older signature format (`ssh-rsa-cert-v01@openssh.com`) and we have use cases where we still have to support older versions of OpenSSH (e.g. bootstrap provisioning/upgrades on devices with older OpenSSH versions baked into their firmware).

I've put together a potential solution that verifies the server version to decide whether to use `{sig_algorithm}-cert-v01@openssh.com`, but not sure if this is the best approach. Let me know what you think, can create a pull request if needed: https://github.com/ronf/asyncssh/commit/f18ead553b84b07434f37da94764ee9902cdc3d0

**Comment by ronf** [comment] 2023-06-02 01:58
I actually did some recent work in this area. See commit 5be289e in the "develop" branch. If you try the latest code in the "develop" branch, does it solve your issue? This should let you use the newer signature algorithms when connecting to host systems that list RSA cert host key algorithms which use the newer signature algorithms, while still using the old signature algorithm on older versions that don't.

**Comment by ronf** [comment] 2023-06-02 02:12
Question: Where are you trying to use RSA certificates? Are you attempting to do certificate-based user authentication, or attempting to do certificate-based host key validation? There are knobs you can set to control which algorithms get used if you are having problems with the defaults that AsyncSSH negotiates, but the details will depend on where certs are being used.

**Comment by kawmarco** [comment] 2023-06-02 03:21
> If you try the latest code in the "develop" branch, does it solve your issue?

Tested on the latest `develop` commit (3760d386a8cf5f7befc760f1d764201aae3bb6c8), issue still persists (tested the changes on f18ead553b84b07434f37da94764ee9902cdc3d0 based on the same commit)

>  Are you attempting to do certificate-based user authentication, or attempting to do certificate-based host key validation?

User auth AFAICT. If it helps, here's the output I get from `sshd -Dddd`:

```
debug2: input_userauth_request: try method publickey [preauth]
userauth_pubkey: unsupported public key algorithm: rsa-sha2-256-cert-v01@openssh.com [preauth]
```

> There are knobs you can set to control which algorithms get used if you are having problems with the defaults that AsyncSSH negotiates, but the details will depend on where certs are being used.

Happy to try them :-)

**Comment by kawmarco** [comment] 2023-06-02 03:53
Did some quick debugging based on https://github.com/ronf/asyncssh/commit/5be289e88876a555224ab8daa169fa9698433a4e, adding the following print statement to `public_key.py`...

```
@@ -2188,6 +2188,7 @@
         """Set the signature algorithm to use when signing data"""
 
         try:
+            print(f"{sig_algorithm=} {_certificate_sig_alg_map.get(sig_algorithm)=}")
             sig_algorithm = _certificate_sig_alg_map[sig_algorithm]
         except KeyError:
             pass
```
...prints:
```
sig_algorithm=b'rsa-sha2-256' _certificate_sig_alg_map.get(sig_algorithm)=None
```

`set_sig_algorithm()` is being called from [`_choose_signature_alg()` in connection.py](https://github.com/ronf/asyncssh/blob/develop/asyncssh/connection.py#L3229) with `keypair.sig_algorithms` as below:
```
keypair.sig_algorithms=(b'rsa-sha2-256', b'rsa-sha2-512', b'ssh-rsa-sha224@ssh.com', b'ssh-rsa-sha256@ssh.com', b'ssh-rsa-sha384@ssh.com', b'ssh-rsa-sha512@ssh.com', b'ssh-rsa')
```

Reversing the `sig_algorithms` tuple so that `b'ssh-rsa'` comes first works for hosts running OpenSSH 7.5, but regresses again on hosts running OpenSSH >=8.8:
```
@@ -3224,7 +3224,8 @@
         """Choose signature algorithm to use for key-based authentication"""
 
         if self._server_sig_algs:
-            for alg in keypair.sig_algorithms:
+            # for alg in keypair.sig_algorithms:
+            for alg in reversed(keypair.sig_algorithms):
                 if alg in self._sig_algs and alg in self._server_sig_algs:
                     keypair.set_sig_algorithm(alg)
                     return True
```

**Comment by ronf** [comment] 2023-06-02 04:45
Thanks for the extra info. I think the recent change I made only really made a difference when choosing the signature algorithm to use for SSH host keys, not users, so that's probably why it didn't make a difference here.

When it comes to choosing signature algorithms for user auth, you correctly identified the code here, and from that you can see that it is looking for whether or not the server sent a list of supported signature algorithms in the "server-sig-algs" SSH extension. If that's not sent, AsyncSSH should always fall back to using the older SHA-1 signature algorithm ('ssh-rsa'). However, if that extension is sent (meaning the server supports the newer SHA-2 algorithms), it will tend to prefer one of those. You can also use the client connection option "signature_algs" to restrict which algorithms are allowed, passing in the subset of algorithms you want it to try. So, if you wanted to restrict the algorithm to the older ssh-rsa on a server that claimed to support the newer algorithms but really didn't, you could pass in `signature_algs=['ssh-rsa']`.

As you discovered, passing this in won't work on newer versions of OpenSSH, though, at least not without a server-side config change, as support for the older SHA-1 based signature algorithms is now disabled by default on OpenSSH.

The message you are getting on the server of "unsupported public key algorithm" makes me wonder if perhaps you are creating the certificate with an algorithm name of "rsa-sha2-256-cert-v01@openssh.com" instead of "ssh-rsa-cert-v01@openssh.com". What do you see for "type" if you run "ssh-keygen -L -f <cert_file>"? I'm not sure older versions of OpenSSH will properly handle anything but the latter, and you shouldn't need to change that in order to be able to use the newer RSA SHA-2 algorithms.

Could you capture a level 2 debug trace showing the SSH handshake with one of the older SSH servers? In particular, I'm curious if the server is advertising support for SHA-2 signatures or not via server-sig-algs. If it is advertising that, I'm curious why selecting a SHA-2 algorithm would be a problem. I think there might be two different problems here, though -- on newer servers with ssh-rsa disabled by default, it will break if you force it to use that, while on older servers it might be getting confused by the public key algorithm name for an RSA cert being anything but "ssh-rsa-cert-v01@openssh.com".

**Comment by kawmarco** [comment] 2023-06-02 06:27
> What do you see for "type" if you run "ssh-keygen -L -f <cert_file>"?

It shows `ssh-rsa-cert-v01@openssh.com`:
```
id_rsa-cert.pub:
        Type: ssh-rsa-cert-v01@openssh.com user certificate
```

Note that [commenting out the original fix from #517](https://github.com/ronf/asyncssh/blob/3760d386a8cf5f7befc760f1d764201aae3bb6c8/asyncssh/public_key.py#L2204-L2208), the server does get me `ssh-rsa-cert-v01@openssh.com` (matching the type on the certificate file).

> ... whether or not the server sent a list of supported signature algorithms in the "server-sig-algs" SSH extension

Inspecting the [`_server_sig_algs` attribute on `_process_ext_info`](https://github.com/ronf/asyncssh/blob/3760d386a8cf5f7befc760f1d764201aae3bb6c8/asyncssh/connection.py#L2090), here's what I get from the different versions:

OpenSSH 7.5:
```
extensions.get(b'server-sig-algs', b'')=b'ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521'
```

OpenSSH 9.1:
```
extensions.get(b'server-sig-algs', b'')=b'ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com'
```

(this matches what's shown in the `kex_input_ext_info:` debug message using `ssh -vvv $host`)

Curiously, v9.1 also has a `ssh-rsa` entry in `server-sig-algs` (which probably explains why reversing `keypair.sig_algorithms` in that experiment regressed on connections to OpenSSH >= 8.8, as it matched `ssh-rsa` entry first).

Comparing regular ssh debug debug output (`ssh -vvv`) on both versions, I noticed one entry that mentions `ssh-rsa` on connecting to a 7.5 host that doesn't appear in 9.1:

```diff
-debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
+debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
```

On the surface, it seems to be choosing the first entry on the host key algorithms list to sign:
```diff
 debug2: sign_and_send_pubkey: using private key ".../ssh/id_rsa" for certificate
-debug3: sign_and_send_pubkey: signing using ssh-rsa-cert-v01@openssh.com
+debug3: sign_and_send_pubkey: signing using rsa-sha2-512-cert-v01@openssh.com
```

**Comment by ronf** [comment] 2023-06-02 22:44
>> What do you see for "type" if you run "ssh-keygen -L -f <cert_file>"?
>
> It shows ssh-rsa-cert-v01@openssh.com:

Ok, good. That's what I'd expect to see, and this doesn't seem related to the issue.

> Curiously, v9.1 also has a ssh-rsa entry in server-sig-algs (which probably explains why reversing keypair.sig_algorithms in that experiment regressed on connections to OpenSSH >= 8.8, as it matched ssh-rsa entry first).

Yeah - the reason to keep ssh-rsa at the end is to make sure it only gets picked as a last resort, when none of the better options are supported. It does seem a bit wrong for OpenSSH to still be listing ssh-rsa if the support for that is actually turned off now by default (like they're doing for the host key algorithms), but any client which supports the RSA SHA-2 algorithms will always choose those over SHA-1, so in practice continuing to list ssh-rsa in the server-sig-algs probably doesn't matter much.

It's good to see that ssh-rsa is at least removed from the host key algorithms. With the recent change I made in AsyncSSH to look at those to decide which signature algorithm to use when acting as a server and signing the host key, it should help fix at least one of the two directions here. However, this won't help with user auth.

> Note that [commenting out the original fix from #517](https://github.com/ronf/asyncssh/blob/3760d386a8cf5f7befc760f1d764201aae3bb6c8/asyncssh/public_key.py#L2204-L2208), the client uses ssh-rsa-cert-v01@openssh.com for both 7.5 and 9.1 (matching the type on the certificate file).

I'm beginning to think that I got the fix in #517 wrong, but I'm not quite sure how to change it to still fix the original problem reported there while not triggering this new error about the algorithm not being recognized. I think I'm going to see if I can reproduce the original issue again, and take a closer look at how OpenSSH fills in the various algorithm names in a case of an RSA cert being used for user auth. In theory, there is a separate signature algorithm field, so it shouldn't be necessary to change the public key alg name to explicitly use the new sig algorithm names. Going with 'ssh-rsa-cert-v01@openssh.com' should always be ok regardless of the signature algorithm used. I think maybe the new algorithms really only need to show up in the list of allowed algorithms (via server-sig-algs in the case of user auth), but there the names never include the "-cert@openssh.com", so that shouldn't impact the cert algorithm name put in the user auth message.

**Comment by ronf** [comment] 2023-06-03 01:38
Ok - I've reproduced the original #517 issue again here, and have confirmed that the fix it contains is required to get user auth using an RSA key signed by a certificate to work, at least when talking to an OpenSSH 9.3p1 server. If it sends an algorithm of ssh-rsa-cert-v01@openssh.com, the server rejects the auth request. If I change it to rsa-sha2-256-cert-v01@openssh.com (matching the sig algorithm actually used), it works.

I guess the next step is to try installing an older version of OpenSSH as a server (like 7.5 or 8.2) and see if there's a way to get RSA keys with certificates and SHA-2 signature algorithms to work and what that looks like in OpenSSH compared with newer versions.

**Comment by ronf** [comment] 2023-06-03 02:50
I wasn't able to get OpenSSH 7.5 or 8.2 to build on my machine under either macOS or Linux (this is an arm64 system), but I was able to get OpenSSH 8.7 to build. What I saw there was kind of strange, though. Connecting via AsyncSSH to OpenSSH 8.7 worked fine with or without the #517 fix. I could use either ssh-rsa-cert-v01@openssh.com or rsa-sha2-256-cert-v01@openssh.com as the public key algorithm with a signature algorithm of rsa-sha2-256, and it worked just fine in both cases.

When I switch to 9.3 as the server, it only works with rsa-sha2-256-cert-v01@openssh.com, requiring #517.

So far, I haven't been able to make things fail with an OpenSSH 8.7 server, or fail on more recent versions with the #517 fix. Could you confirm what combination is failing for you where you had to back out the #517 change for things to work?

**Comment by ronf** [comment] 2023-06-03 03:17
A bit more info: When I add "PubkeyAcceptedAlgorithms +ssh-rsa-cert-v01@openssh.com" to the sshd_config on newer versions of OpenSSH, I can get it to work just like 8.7, where auth is successful with or without the #517 change. Basically, it looks like OpenSSH is rejecting the auth since "ssh-rsa-cert-v01@openssh.com" is no longer allowed by default, even though it is possible to use that with newer SHA-2 signature algorithms. So, the one way to get auth to succeed without manually enabling "ssh-rsa-cert-v01@openssh.com" is to switch the public key algorithm over to a different RSA cert algorithm, such as "rsa-sha2-256-cert-v01@openssh.com".

I guess you might be running into a problem where the OpenSSH you are using is new enough to understand RSA SHA-2 (which was added in 7.2, I think), but old enough to not yet understand the certificate versions of the RSA SHA-2 algorithms, which appear to have come in around 7.8. So, I'd expect 8.2 to work ok with the #517 fix, but maybe not 7.5. Does that match what you are seeing?

**Comment by ronf** [comment] 2023-06-03 03:22
This makes me wonder if OpenSSH itself handles this case correctly, where a new OpenSSH client is trying to talk to an older server that supported the RSA SHA-2 signature algorithms but didn't support the RSA SHA-2 cert algorithms. Can you reproduce the failure in that case with a newer client (8.8+) talking to your 7.5 server? If not, I wonder what the client sends for the public key algorithm in the auth request, and how it knows what the remote system supports, since server-sig-algs doesn't list cert algorithms.

**Comment by ronf** [comment] 2023-06-03 19:13
Thinking about this overnight, I'm guessing the situation is something like the following depending on OpenSSH server version:

OpenSSH 7.4 and earlier: No server-sig-algs advertised, so only ssh-rsa-cert-v01@openssh.com will be used, with a signature algorithm of ssh-rsa (SHA-1).

OpenSSH 7.5 to 7.7: Server-sig-algs advertised with RSA SHA-2 signature algs, but there's no support for the cert versions of these algorithms as a valid public key type, so the change in #517 breaks things on those servers when attempting to use RSA SHA-2 signatures.

OpenSSH 7.8 ro 8.7: Server-sig-algs advertised and there's support for the cert versions of these as public key types, so things work with either SHA-1 or SHA-2 RSA signatures.

OpenSSH 8.8 and later: Same as the last case, except that ssh-rsa and its corresponding cert version are disabled by default, so an RSA SHA-2 signature algorithm MUST be chosen. This should happen automatically, as long as you don't limit signature algs in AsyncSSH to only SHA-1.

To fix the 7.5-7.7 issue, you should be able to set `signature_algs=['ssh-rsa']` when making an outbound connection. This will force RSA SHA-1 to be used, but doing that will make sure the public key algorithm in the auth request is ssh-rsa-cert-v01@openssh.com, which should be accepted by the server. This isn't as good as what happened before #517 on these versions, where ssh-rsa-cert-v01@openssh.com was used as the public key type while still allowing SHA-2 signatures, but at least authentication should work again without having to back out #517. Unfortunately, you need to do this selectively, as limiting the signature to just ssh-rsa won't work by default against OpenSSH 8.8 and later.

To provide full control here, I'd probably need to look at implementing the equivalent of the PubkeyAcceptedAlgorithms config option from OpenSSH, and then use that to filter the allowed public key types independent of the existing filtering based on allowed signature algs. This would be a somewhat messy change, though, as it might mean attempting to authenticate with the same key multiple times with different public key types in the auth requests, and the current code is not really set up to do that. If setting signature_algs to just ssh-rsa works for you, I think that might be the best option for now.

**Comment by kawmarco** [comment] 2023-06-06 06:18
>  Can you reproduce the failure in that case with a newer client (8.8+) talking to your 7.5 server?

Yes, comparing the versions below built from the [openssh portable release source](https://www.openssh.com/portable.html):
```diff
-OpenSSH_8.0p1, OpenSSL 1.1.1k  FIPS 25 Mar 2021
+OpenSSH_8.9p1, OpenSSL 1.1.1k  FIPS 25 Mar 2021
```

The 8.0 client connects successfully with both 7.5 and 9.3 servers, while the 8.9 client falls back to password auth. Comparing `ssh -v` between the two versions:

```diff
 debug1: Offering public key: .../ssh/id_rsa RSA-CERT SHA256:... explicit
-debug1: Server accepts key: .../ssh/id_rsa RSA-CERT SHA256:... explicit
-debug1: Authentication succeeded (publickey).
+debug1: send_pubkey_test: no mutual signature algorithm
```

The `no mutual signature algorithm` message might be notable as it suggests it's detecting the lack of support for the desired signature algorithm name when connecting to 7.5 servers.

> If setting signature_algs to just ssh-rsa works for you, I think that might be the best option for now.

Sounds good to me, I did some limited testing to add a connection attempt using this option to our logic and it seems to work well 👍 

I'll finish up testing with our different server versions/use-cases that we have to support just to be sure, but I'm feeling confident this will work for us (will update the issue tomorrow with results).

**Comment by kawmarco** [comment] 2023-06-08 00:50
Hi @ronf, the `signature_algs=['ssh-rsa']` workaround works for our use case, thank you so much for taking the time following through the analysis on this issue, it's extremely appreciated!

**Comment by ronf** [comment] 2023-06-10 00:45
Glad to hear that setting signature_algs is working for you here, @kawmarco.

I've been thinking about if there's a simple and clean way to make this decision automatically, but there aren't many options beyond what you proposed in f18ead5 to do this. In order to avoid OpenSSH rejecting the algorithm being set to `ssh-rsa-cert-v01@openssh.com`, it's necessary to change the certificate algorithm name to one of the RSA SHA-2 names. However, doing that will break when talking to OpenSSH 7.5 to 7.7 and there's nothing sent in the various algorithm lists that tell us that this will be the case. So, that leaves only the option to match on the server version and then propagate that all the way down into the `set_sig_algorithm` method on `SSHKeyPair` to decide which algorithm name to use.

I did have one other idea, which is basically to try with the RSA SHA-2 algorithm name and then fall back to the original cert algorithm name if that doesn't work. One nice thing about that is that it wouldn't be OpenSSH-specific. I'm not sure how easy it will be to do, but I'll play around with that idea this weekend and let you know how it goes.

**Comment by ronf** [comment] 2023-06-10 03:10
Ok - I've got an initial prototype of the change mentioned above:

```patch
diff --git a/asyncssh/connection.py b/asyncssh/connection.py
index 9d21827..198d39b 100644
--- a/asyncssh/connection.py
+++ b/asyncssh/connection.py
@@ -3074,6 +3074,7 @@ class SSHClientConnection(SSHConnection):

         self._client_keys: List[SSHKeyPair] = \
             list(options.client_keys) if options.client_keys else []
+        self._saved_rsa_key: Optional[_ClientHostKey] = None

         if options.preferred_auth != ():
             self._preferred_auth = [method.encode('ascii') for method in
@@ -3314,16 +3315,27 @@ class SSHClientConnection(SSHConnection):
         if not self._host_based_auth:
             return None, '', ''

+        key: Optional[_ClientHostKey]
+
         while True:
-            try:
-                key: Optional[_ClientHostKey] = self._client_host_keys.pop(0)
-            except IndexError:
-                key = None
-                break
+            if self._saved_rsa_key:
+                key = self._saved_rsa_key
+                key.algorithm = key.sig_algorithm + b'-cert-v01@openssh.com'
+                self._saved_rsa_key = None
+            else:
+                try:
+                    key = self._client_host_keys.pop(0)
+                except IndexError:
+                    key = None
+                    break

             assert key is not None

             if self._choose_signature_alg(key):
+                if key.algorithm == b'ssh-rsa-cert-v01@openssh.com' and \
+                        key.sig_algorithm != b'ssh-rsa':
+                    self._saved_rsa_key = key
+
                 break

         client_host = self._options.client_host
@@ -3382,10 +3394,19 @@ class SSHClientConnection(SSHConnection):

                 self._client_keys = list(load_keypairs(result))

-            keypair = self._client_keys.pop(0)
+            if self._saved_rsa_key:
+                key = self._saved_rsa_key
+                key.algorithm = key.sig_algorithm + b'-cert-v01@openssh.com'
+                self._saved_rsa_key = None
+            else:
+                key = self._client_keys.pop(0)
+
+            if self._choose_signature_alg(key):
+                if key.algorithm == b'ssh-rsa-cert-v01@openssh.com' and \
+                        key.sig_algorithm != b'ssh-rsa':
+                    self._saved_rsa_key = key

-            if self._choose_signature_alg(keypair):
-                return keypair
+                return key

     async def password_auth_requested(self) -> Optional[str]:
         """Return a password to authenticate with"""
diff --git a/asyncssh/public_key.py b/asyncssh/public_key.py
index a590c2b..1ce5f8d 100644
--- a/asyncssh/public_key.py
+++ b/asyncssh/public_key.py
@@ -2201,11 +2201,6 @@ class SSHKeyPair:

             cert = cast('SSHX509CertificateChain', self._cert)
             self.public_data = cert.adjust_public_data(sig_algorithm)
-        else:
-            if sig_algorithm.endswith(b'@openssh.com'):
-                sig_algorithm = sig_algorithm[:-12]
-
-            self.algorithm = sig_algorithm + b'-cert-v01@openssh.com'

     def sign(self, data: bytes) -> bytes:
         """Sign a block of data with this private key"""
```

This backs out change #517, in favor of the new approach where the calling code will attempt to authenticate with RSA keys first with just the signature algorithm change, and then if that is rejected it will try again with the certificate algorithm changed, so that it can work on OpenSSH 7.8+ where `ssh-rsa-cert-v01@openssh.com` is not allowed as a certificate algorithm.

The code here should cover both public key authentication and host-based authentication. It should only be active when RSA keys signed by a certificate are used, and only when attempting to use a SHA-2 signature algorithm with that key.

**Comment by ronf** [comment] 2023-06-11 14:22
The change above (with an added comment) is now checked in as commit 10bd9a7 in the "develop" branch, replacing change #517.

**Comment by kawmarco** [comment] 2023-06-12 13:24
Thanks so much for following up on this, can confirm this works well for our use cases :-)

Checked-out https://github.com/ronf/asyncssh/commit/10bd9a795bf3f3207f85892cd53366abe2b6f0c0 in our test environment, it's connecting to servers running OpenSSH from 7.5 to 9.3 successfully.

**Comment by ronf** [comment] 2023-06-12 13:58
Great - thanks for the confirmation! This change will be included in the next release.

**Comment by ronf** [comment] 2023-06-22 03:58
This change is now available in AsyncSSH 2.13.2.

**Closed by ronf** 2023-06-22 03:58 UTC

**Comment by htol** [comment] 2023-07-14 14:08
Hi @ronf is it possible for adding same support for 'ssh-ed25519-cert-v01@openssh.com' keys? Last working version was 2.5.0 and remote server is openssh 8.7.

**Comment by ronf** [comment] 2023-07-15 04:10
The issue here is only applicable to RSA keys, as RSA is the only key type which has multiple signature algorithms associated with it. For ed25519 and other key types, neither this change or the previous one apply. If you're seeing a problem with ssh-ed25519 certificates, it's probably a different issue.

I just did a test here, and they seem to be working fine for me in AsyncSSH. In fact, that's what I have been using by default for many years now. I also don't see any changes between 2.5.0 and 2.6.0 which are related to Ed25519 support.

Can you capture debug output showing the problem? What kind of failure is being reported?
