### ISSUE TITLE
Is it possible to open a remote shell and hand over interactive control to the local user?

### ISSUE THREAD

**Issue by oliwarner** [ronf/asyncssh#70] opened 2016-12-16 11:52 UTC
Apologies for the question (rather than a bug report) but is it possible to open a connection to a remote server and then start a shell?

The scenario is I have a very convoluted chain of servers to connect over. `asyncssh` is perfect for running one-off commands and pulling the output back. I do that elsewhere. But I need to give a local command line user, remote command line access over this same chain. Is there a good way I can plug this in to the local terminal?

**Comment by ronf** [comment] 2016-12-17 03:15
There's nothing built into AsyncSSH to attach a remote shell session directly to the local terminal the way the regular 'ssh' binary would. You can get close with something like:

```python
import asyncio, asyncssh, sys

async def run_client():
    async with asyncssh.connect('localhost') as conn:
        await conn.run(term_type='xterm', stdin=sys.stdin,
                       stdout=sys.stdout, stderr=sys.stderr)

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

However, trying to run something like "vi" from within that shell won't work right. I haven't really looked closely at why.

**Comment by costrouc** [comment] 2017-01-05 01:37
@oliwarner I am not around my computer so I will make sure to get to this tomorrow morning. I have done exactly this with aiohttp + asyncssh + xterm.js. emacs, vim, etc. work just fine so it is possible.

**Comment by ronf** [comment] 2017-02-12 15:43
@costrouc, would you mind sending a pointer to the code you mentioned here?

Thanks!

**Comment by theblazehen** [comment] 2017-03-05 09:13
Any way to do it for the server side?

**Comment by ronf** [comment] 2017-03-05 15:09
It would be possible on the server side to call the standard library asyncio.create_subprocess_exec() and get back a set of pipes to a local process's stdin/stdout/stderr and then feed data back and forth from AsyncSSH's incoming connection's stdin/stdout/stderr to those. However, there's no equivalent in AsyncSSH yet of an SSHClientProcess on the server side, so there isn't a way to have AsyncSSH automatically redirect the existing SSHReader and SSHWriters to the pipes that create_subprocess_exec() returns. I'd need to think a bit to figure out how to allow the server side over to support processes while still maintaining backward compatibility.

**Comment by ronf** [comment] 2017-04-14 04:54
I've just checked in support for server-side I/O redirection, in the form of a new SSHServerProcess class that provides capabilities similar to SSHClientProcess. To use it, you specify a new process_factory argument to create_server() or listen() in place of the old session_factory. When new sessions are accepted on the SSH server, it calls this factory with a single SSHServerProcess argument instead of stdin, stdout, and stderr streams. This new process class has these streams as members, but also supports a redirect() method similar to SSHClientProcess. Here's an example:

```python
import asyncio, asyncssh, subprocess, sys

async def handle_client(process):
    bc_proc = subprocess.Popen('bc', shell=True, stdin=subprocess.PIPE,
                               stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    await process.redirect(bc_proc.stdin, bc_proc.stdout, bc_proc.stderr)
    await process.stdout.drain()
    process.exit(0)

async def start_server():
    await asyncssh.listen('', 8022, server_host_keys=['ssh_host_key'],
                          authorized_client_keys='ssh_user_ca',
                          process_factory=handle_client)

loop = asyncio.get_event_loop()

try:
    loop.run_until_complete(start_server())
except (OSError, asyncssh.Error) as exc:
    sys.exit('Error starting server: ' + str(exc))

loop.run_forever()
```

This example launches the 'bc' calculator when a new SSH session is requested and pipes data from the client through to this 'bc' process. When the 'bc' process exits (generally due to EOF on stdin), the SSH process exits as well.

Comments and suggestions are welcome. I'll try to get a release out with this capability in the next couple of weeks if no concerns are raised.

**Comment by ronf** [comment] 2017-05-06 02:49
This feature is now available in AsyncSSH version 1.10.0.

**Closed by ronf** 2017-05-06 02:49 UTC
Labels: enhancement

**Comment by ninghaoyu** [comment] 2019-01-28 02:36
> There's nothing built into AsyncSSH to attach a remote shell session directly to the local terminal the way the regular 'ssh' binary would. You can get close with something like:
> 
> ```python
> import asyncio, asyncssh, sys
> 
> async def run_client():
>     async with asyncssh.connect('localhost') as conn:
>         await conn.run(term_type='xterm', stdin=sys.stdin,
>                        stdout=sys.stdout, stderr=sys.stderr)
> 
> try:
>     asyncio.get_event_loop().run_until_complete(run_client())
> except (OSError, asyncssh.Error) as exc:
>     sys.exit('SSH connection failed: ' + str(exc))
> ```
> 
> However, trying to run something like "vi" from within that shell won't work right. I haven't really looked closely at why.

hi, ronf this problem not fix ....  . I make a ssh proxy need this feature, how should I do ?

**Comment by ronf** [comment] 2019-01-30 05:40
I'm hesitant to try and provide full SSHD-like functionality here, as AsyncSSH really doesn't support the ability to do true authentication against the list of users on the underlying OS. It also doesn't provide any kind of ability to switch which user any subprocesses it starts run as. So, if you try to run actual processes on the machine AsyncSSH is running on, they will all run as the user which started up AsyncSSH, regardless of what user actually authenticated.

A better option here would probably be to use AsyncSSH as a proxy which connected to the actual system SSHD to execute the requested commands. Users would authenticate to the proxy (based on AsyncSSH), and then AsyncSSH would open an outbound SSH connection to the real SSHD running either on localhost or potentially some other server that it was configured to act as a proxy for. Each time a user then requested either a shell or to run a command or subsystem, the proxy could apply whatever policy it wanted to and if allowed make an outbound connection to the real SSHD and then start a session there with the stdin/stdout/stderr redirected back to the original inbound connection's session.

Here's an example of the redirection part, but for simplicity in this example I just have it opening a single upstream connection as the user who runs this AsyncSSH proxy and forwarding all requests to that, rather than actually trying to manage separate connections for each inbound user and authenticating them separately.

This example supports both running commands and running an interactive shell, and can successfully run things like 'vi':

```python
import asyncio, asyncssh, sys
  
async def handle_session(process):
    result = await conn.run(command=process.command, encoding=None,
                            term_type=process.get_terminal_type(),
                            term_size=process.get_terminal_size(),
                            stdin=process.stdin, stdout=process.stdout, 
                            stderr=process.stderr)

    process.exit(result.exit_status)

async def start_server():
    global conn

    conn = await asyncssh.connect('localhost')

    await asyncssh.listen('', 8022, server_host_keys=['ssh_host_key'],
                          authorized_client_keys='ssh_user_ca',
                          process_factory=handle_session, 
                          session_encoding=None)

loop = asyncio.get_event_loop()

try:
    loop.run_until_complete(start_server())
except (OSError, asyncssh.Error) as exc:
    sys.exit('Error starting server: ' + str(exc))

loop.run_forever()
```

**Comment by bashkirtsevich** [comment] 2019-01-30 17:54
Hi @ronf ! Is it possible to run `bash` as subprocess and enable/emulate TTY? `stdin`, `stdout` works finally, but without command line prompt.

**Comment by ronf** [comment] 2019-01-31 02:43
If you specify term_type when you make the upstream connection, AsyncSSH will request a TTY when opening the session on the upstream server. This should allow you to get things like prompts and allow applications like "vi" to work. In the proxy example I posted here, requesting a TTY in the inbound connection and passing in the terminal type should automatically trigger an equivalent request on the server side. This happens automatically for interactive shell requests, but if you are passing in a command to run you need to request a TTY explicitly by using the "-t" option in the SSH client.

**Comment by bashkirtsevich** [comment] 2019-02-15 18:53
Hello again. I try to set tunnel between local and remote server, my code looks like:
```python
import asyncio
import crypt
import sys

import asyncssh

passwords = {
    'guest': '',  # guest account with no password
    'user123': 'qV2iEadIGV2rw'  # password of 'secretpw'
}


async def exec_process(process):
    async with asyncssh.connect('192.168...', username='user', password='password') as conn:
        result = await conn.run(
            command=process.command,
            encoding=None,
            term_type='xterm',
            # term_type=process.get_terminal_type(),
            # term_size=process.get_terminal_size(),
            stdin=process.stdin, stdout=process.stdout,
            stderr=process.stderr)

        process.exit(result.exit_status)


class MySSHServer(asyncssh.SSHServer):
    def connection_made(self, conn):
        print('SSH connection received from %s.' %
              conn.get_extra_info('peername')[0])

    def connection_lost(self, exc):
        if exc:
            print('SSH connection error: ' + str(exc), file=sys.stderr)
        else:
            print('SSH connection closed.')

    def begin_auth(self, username):
        return passwords.get(username) != ''

    def password_auth_supported(self):
        return True

    def validate_password(self, username, password):
        pw = passwords.get(username, '*')
        return crypt.crypt(password, pw) == pw


async def start_server():
    await asyncssh.create_server(
        MySSHServer, '', 8022,
        server_host_keys=['ssh_host_key'],
        process_factory=exec_process,
    )


if __name__ == '__main__':
    loop = asyncio.get_event_loop()

    try:
        loop.run_until_complete(start_server())
    except (OSError, asyncssh.Error) as exc:
        sys.exit('Error starting server: ' + str(exc))

    loop.run_forever()
```
And when I connect, process factory ends immediately (jump to `process.exit` gracefully). When I open session with `stdin=sys.stdin, stdout=sys.stdout, ...` its work fine in my console. 
`command=process.command` -- here `process.command` eq `None` (any other values has no good result). How to establish session? And why `await conn.run(...)` exit so fast?

**Comment by ronf** [comment] 2019-02-16 04:08
I'm not sure why you're getting to process.exit() so quickly, but I think the "unsupported operand type(s) for &=" is caused by the fact that SSHProcess.exit() requires you to pass an integer value, and so you shouldn't be calling it when result.exit_status is `None`. That code should probably be changed to:

```python
        if result.exit_status is not None:
            process.exit(result.exit_status)
        else:
            process.close()
```

Even this is technically not quite right -- if you want to preserve exit signals, you'd need something like:

```python
        if result.exit_signal:
            process.exit_with_signal(*result.exit_signal)
        elif result.exit_status is not None:
            process.exit(result.exit_status)
        else:
            process.close()
```

Getting back to your main question, though, how are you invoking ssh to connect to the server you show here? Are you sure you're passing in a valid stdin? The exec_process() function here would exit right away if stdin was already closed.

**Comment by bashkirtsevich** [comment] 2019-02-16 08:40
Thanks for you help.

In my case I've try to extend [your solution](https://github.com/ronf/asyncssh/issues/70#issuecomment-458819014) with custom authorization.

**Comment by bashkirtsevich** [comment] 2019-02-16 08:54
Ha-ha, I've got it!
```python
    await asyncssh.create_server(
        MySSHServer, '', 8022,
        server_host_keys=['ssh_host_key'],
        process_factory=exec_process,
        session_encoding=None
    )
```
After adding `session_encoding=None` _(and PyCharm show leak warning, that it should be string value)_ its finally works. Rhetorical question, why that parameter was change `conn.run` behavior? Encoding conflicts?

Thanks for your help, and my I add my solution to your examples through PR?

**Comment by ronf** [comment] 2019-02-16 15:32
Glad you found it - I must admit I missed that myself when reading your example code.

As for the naming, the create_server() command had a need to pass in a "server_factory" as well as a "session_factory". When I later added other parameters (specifically, "encoding" and "errors") that applied only at the time new sessions were created, I wanted to name them such they it was clear they were tied to new sessions as they were created. For "errors" in particular, it felt like not having that prefix would be confusing, as you wouldn't know what errors that was referring to.

In retrospect, I can see how this is confusing in other ways, as many other functions accept a "session_factory" argument when creating a session and use the arguments "encoding" and "errors". There, you're generally creating a new session during that call, so it's more clear what those are associated with, but the change in naming could still lead to a mistake like this.

When I later added "process_factory" as an alternative to "session_factory", I also had a problem where you still had to pass "session_encoding" and "session_errors" even though you weren't passing "session_factory" any more, so the naming didn't line up.

Since this only affects create_server() and listen(), it might be time for me to reconsider the naming, and just provide backward compatibility for the old names.

As for adding this as a new example, I'm still a bit nervous about encouraging people to provide a tunneling capability like this without really thinking through how to do the access control properly. While it's a bit better when you pass the username/password through, I don't think I'd want the example to do its own password validation in that case, especially not with crypt() style passwords as they are very easy to crack. I used that in another example because I wanted to focus on the AsyncSSH-related stuff rather than how to do secure password hashing, but I should probably change that to use a stronger hash or at least add some warning text about not putting that in real code.

**Comment by ronf** [comment] 2019-02-20 05:31
I just pushed commit 766db60 in the "develop" branch with a change to rename "session_encoding" and "session_errors" to just "encoding" and "errors" in create_server() and listen(), matching the naming used everywhere else. Hopefully this will prevent others from running into the issue you saw here.

The old names will continue to work for some time, but they now trigger deprecation warning messages suggesting the that shorter names be used.

**Comment by mumutu66** [comment] 2019-04-01 08:25
is there any way to revert the redirect  made by  `process.redirect`

**Comment by ronf** [comment] 2019-04-01 18:03
Right now, any change made by redirect() will trigger a call to close() on the previously set reader/writer. So, It's not possible to return to using the previously set reader/writer. Depending on the type of source/target, it may be possible to pass that in again to create a new reader/writer for it again, but in most cases the close() call would prevent that. Could you say a little more about the use case you have in mind and what type of streams you would be passing in?

**Comment by mumutu66** [comment] 2019-04-02 01:46
@ronf thanks for your explanation  I am new to this and working on a server turn `kubectl exec` into `SSH` and it has a plane to list all the pods under some namespaces after input a selection the process redirect the IO to user  and when receive a break the process spawned by `kubectl` will be killed and I want to the process back to the list plane. a straightforwards thought is the IO redirect can be reverted ..so how can I achieve something like this...

**Comment by ronf** [comment] 2019-04-03 02:26
I'm not sure I'm completely following you, but you'd probably be better off in this case leaving the SSH connection directed to pipes (the default), and reading the output and then writing it out to the user yourself.

Alternately, you might want to think about using different SSH sessions for each operation you want to perform. This can all be done over a single SSH connection, so you'd only be authenticating once and the connection could be kept open. However, with each command running as its own session/channel, you'd be able to use separate redirection on each, and you'd be able to get back EOF properly for the kubectl command without interfering with any other sessions you open.

**Comment by mumutu66** [comment] 2019-04-03 11:06
@ronf thanks a lot~it's just what I need

**Comment by ronf** [comment] 2019-04-03 14:47
Great - I'd suggest you look into the run() method on SSHClientConnection() and see if that will work for you here. You can either get all the output back in the SSHCompletedProcess object, or you can use I/O redirection to send the output from that command somewhere else, similar to the example at https://asyncssh.readthedocs.io/en/latest/#i-o-redirection. This won't affect any other sessions you might have opened on that same connection, each of which can have separate I/O redirection applied to them.
