### ISSUE TITLE
Not all packets shown with debug level 3

### ISSUE THREAD

**Issue by matthijskooijman** [ronf/asyncssh#131] opened 2018-03-02 14:25 UTC
Packet logging now tries to log packets in the proper logger (AuthHandler or Channel), which means packets are logged by `SSHPacketHandler.process_packet`. However, this also means that only packets that are not being processed will be handled. In particular,
 - Any [initially ignored kex packet](https://github.com/ronf/asyncssh/blob/master/asyncssh/connection.py#L741-L743) is not logged
 - Any [channel messages for unknown channels](https://github.com/ronf/asyncssh/blob/master/asyncssh/connection.py#L1661) are not logged.

I was a bit surprised by this when debugging an issue with invalid channel ids. IMHO it would be worth considering *all* packets early and unconditionally in `SSHConnection`, so that the debug output is 100% accurate, even if that means all packets are logged in the connection logger instead of the channel or auth loggers.

**Comment by ronf** [comment] 2018-03-04 04:27
Thanks for catching this!

I can confirm that both of the areas you listed here have this problem, but it seems like other cases are well covered, even when getting something like an incomplete packet that eventually triggers a failure during processing.

The only other edge case I see right now is in SFTP if a packet comes in which doesn't contain a packet type or packet id (meaning it is less than 5 bytes), but that would be a bit messy the way the code is structured right now and I'm not sure that's a very interesting case. Like regular SSH packets longer SFTP packets that are discovered to be incomplete during processing are logged correctly.

I'm going to add a "log_unprocessed_packet" function which can be used to cover the cases you list here and any future cases where the code decides not to process a packet for some reason, and I'll also provide a way to give the reason the packet was not processed in the output.

**Comment by ronf** [comment] 2018-03-04 05:45
A fix for this is now checked into the "develop" branch - thanks again for the report!

**Comment by matthijskooijman** [comment] 2018-03-04 08:47
Thanks. I had a look at the commits, looks like that would indeed catch them all, though the code for this is getting a bit complex (so it's easy to change the code later and miss a case for logging, I guess).

Would it not be better to let `SSHConnection` handle all logging instead? E.g. before it calls `_auth.process_packet()`, let it log the packet to `_auth.logger`? For channel messages, a similar thing could happen, but that probably works better if an extra case is added [here](https://github.com/ronf/asyncssh/blob/master/asyncssh/connection.py#L749) to process channel messages, instead of calling `_process_channel_msg()` through the handler table? If so, then whatever happens, [this bit of code](https://github.com/ronf/asyncssh/blob/master/asyncssh/connection.py#L740-L752) is responsible to log the packet in some way.

**Comment by ronf** [comment] 2018-03-04 15:23
I agree that the current implementation is kind of ugly. Even before this change, I really didn't like having to add the "log" flag in the call to process_packet, and even worse to manually add the list of packet types to _excluded_recv_pkttypes. When I first coded that, I wasn't sure how many levels deep I would go when adding making decisions about the right level to do the logging at to maximize context information. I figured that in some cases, I could even end up multiple steps away from the connection module and wanted a way for each module to just have to know if it was its responsibility to log or not. I was also trying to avoid having to same separate calls to process_packet and log_packet, at least in the common case.

Now that I have a more complete picture of where the current logging is, I'll take another look, though.

**Comment by ronf** [comment] 2018-03-04 18:29
I took another look at this today, Matthijs, and it turned out not to be too difficult to rework the code along the lines of what you suggested. The new version is now checked into the develop branch. Thanks for suggesting this, and I'd love to know what you think of the change.

**Comment by matthijskooijman** [comment] 2018-03-05 08:35
Yeah, this looks a lot better and cleaner. One more thing I would change is to move the logging out of `process_packet` and put it here: https://github.com/ronf/asyncssh/blob/56a8c99188382b68e678d47dcbf54a6cf9b74f1f/asyncssh/connection.py#L759

Then that code really has full control over the logging, without relying on `process_packet` to handle a part of it.

**Comment by ronf** [comment] 2018-03-06 07:26
Ok - take a look at the latest couple of checkins. This removes the logging from process_packet() completely and pretty much all the other logging-related code in SSHPacketHandler. I still have a split between SSHPacketHandler and SSHPacketLogger, though, since SFTP uses only SSHPacketLogger and has its own slightly different process_packet() mechanism.

With this round of changes, I also managed to remove the need to explicitly pass the dict of handler_names around, which always bugged me. In the send_packet() call, I still need to pass the handler which is initiating the send, but I now call back into that handler to actually do the packet logging, so it automatically picks up the right handler names. I like that a lot better.

**Comment by matthijskooijman** [comment] 2018-03-06 09:38
Looking good, things are getting cleaner by the commit. I'm out of suggestions for the code :-)

As for the commits: Are you planning to squash things together (or perhaps re-divide the changes in different logical commits), or do you want to push the commits as-is? I have a strong personal preference for a clean commit history that does not need to show development steps, but YMMV :-)

**Comment by ronf** [comment] 2018-03-06 14:39
Thanks for all your suggestions. :)

Regarding the commit history, I'm not a git expert but my understanding is that it can be dangerous to do any squashing of the commit history once it has made it onto a public branch. I do some cleanup of my local commits before I push things, but in a case like this where I'm sharing my incremental development or where I only notice a mistake after I've pushed something, an occasional extra commit that I'd normally squash makes it out there (like the most recent commit here).

If I'm wrong about this and there's a way to safely change the commit history even after pushing to the public "develop" branch, I'd love to learn more about how that can be done!

The other thing that I struggle with is making changes to TravisCI config files. I have to push those to get Travis to see them, and I often end up with a string of public commits trying to get a change right on that. If I do things quickly enough, I'll sometimes squash those even though they're public when I'm done hoping no one has picked up the intermediate changes, but I have actually seen that break something like my Appveyor builds if they're still in progress when I do that, so it's probably not a good idea even there.

**Comment by matthijskooijman** [comment] 2018-03-06 18:11
> Regarding the commit history, I'm not a git expert but my understanding is that it can be dangerous to do any squashing of the commit history once it has made it onto a public branch.

Well, yes and no. *if* you change history on a branch, than anyone who has pulled that branch might end up with an unexpected history (in particular duplicate commits and conflicts) when they pull from the branch again. So this might need some additional care when pulling from such a branch.

In general, this means that rewriting history on a stable, public branch such as master or a release branch is not acceptable. With other branches (feature branches, temporary branches, pull request branches), users are less suprised when rewriting happens, or these branchens might not have been pulled at all. So it ends up being a matter of per-repository policy. A rule of thumb that I just realized, is that if a branch is ok to delete, it is probably ok to rewrite history.

In this particular case, it depends on the status you assign to this "develop" branch. Is that a placeholder branch for wip, but should people track master? Then rewriting develop might be acceptable. But if develop is the branch that collects commits during development, which are merged to master on a release, then it would be better to have develop stable without rewriting.

In either case: It might have been better to push these changes to a feature branch "log-improvements" or something, where rewriting would certainly be ok :-)

> The other thing that I struggle with is making changes to TravisCI config files. I have to push those to get Travis to see them, and I often end up with a string of public commits trying to get a change right on that. If I do things quickly enough, I'll sometimes squash those even though they're public when I'm done hoping no one has picked up the intermediate changes, but I have actually seen that break something like my Appveyor builds if they're still in progress when I do that, so it's probably not a good idea even there.

This would be easily solved by pushing to a separate branch, I guess? Unless TravisCI only looks at specific branches?

**Comment by ronf** [comment] 2018-03-08 05:08
Yeah, I think the bottom line here is that I should get into a habit of creating short-lived branches off of "develop" for work in progress I want to publish rather than doing them in "develop" directly, and then cleaning up the branch when the work is done, allowing me to clean up the revision history before merging it. That way, "develop" can be used as I originally intended it, as a place to pick up bleeding edge changes not in an official release yet.

Regarding TravisCI, I thought I had set it up to only build specific branches, but when I looked closer that wasn't the case, so I could probably use the same approach there.

**Comment by matthijskooijman** [comment] 2018-03-08 08:37
Yup, that sounds like a good approach for the future. Best to leave `develop` is it is now.

> Regarding TravisCI, I thought I had set it up to only build specific branches, but when I looked closer that wasn't the case, so I could probably use the same approach there.

Even then, you could configure it for a "travis-test" branch and do your testing there :-)

**Comment by matthijskooijman** [comment] 2018-03-08 08:37
I guess that makes this issue fixed?

**Comment by ronf** [comment] 2018-03-09 06:47
Yes - I'll leave this open for now, though, and close it as soon as I have a release out which contains the fix (which should be in a few days).

**Comment by ronf** [comment] 2018-03-13 05:04
This fix is now released in AsyncSSH 1.12.1.

**Closed by ronf** 2018-03-13 05:04 UTC
