### ISSUE TITLE
Asyncssh.scp seem's to have trouble with file names that have space's in them.

### ISSUE THREAD

**Issue by knkp** [ronf/asyncssh#253] opened 2020-02-14 01:20 UTC
First I gotta say, as I've been digging into this library trying to figure out what's wrong I've been more and more impressed with the design behind it. Learned a lot just reading the code. 
Thank you for all your hard work.

OK, I wouldn't be surprised if it's just something I'm doing wrong or maybe I've wandered into a taboo. But I cannot get scp to push files to a server if they have space's in the names. Trying to do this under Windows 10 and I'm working with asyncssh==1.18.0

I've tried several methods to trace what's going on and it always come's back to asyncssh is aware of the file all the way up to the point that it tries that actual transfer and it fails with:
`bytearray(b'\x01scp: Invalid copy or dir request\n')`
I took that from a print statement I added located in 
```
SSHChannel:
 ...
def _flush_send_buf(self)
```

I have tried some of the wildcard patterns, replacing the space in the filename with * and ?.
I also replaced the `\\` with `/ ` because I found out that the matching requires this in order for it to work it's way through a path.

I see that eventually, it _does_ match to the file, and then it replaces the special character's with the space again and tries to send. Which then fails.

I'm sending it this way:
```
async with asyncssh.connect(self.SERVER_HOST, self.PORT, client_keys=self.CLIENT_KEY) as conn:
    await asyncssh.scp('c:/somepath/example with spaces.txt',(conn, b'.'))
```

This works for me under test with file names that do not have space's. But for the life of me I can't get it to work with them.

Thanks for any insight.

**Comment by knkp** [comment] 2020-02-14 03:30
OK, it's working for me now. 
Just needed to change 
`def _parse_cd_args(args):` 
so that
`permissions, size, name = args.split()`
is only splitting twice. This way spaces are preserved in the filename. Now it's working for me. 

Hope someone else finds this useful!

**Comment by ronf** [comment] 2020-02-14 03:34
I did some testing here just now and was unable to reproduce this problem. I tested it on both Windows and MacOS, and both cases worked fine with a filename with multiple spaces in it, but I was using AsyncSSH only as a client, not a server. In your testing, were you using AsyncSSH on both sides?

**Comment by knkp** [comment] 2020-02-14 03:40
I knew I forgot a detail. Yes I was.

**Comment by ronf** [comment] 2020-02-14 03:46
Ok, thanks! I think I've been able to reproduce it here. Was this the change you had in mind?

```patch
@@ -43,7 +43,7 @@ def _parse_cd_args(args):
     """Parse arguments to an SCP copy or dir request"""
 
     try:
-        permissions, size, name = args.split()
+        permissions, size, name = args.split(None, 2)
         return int(permissions, 8), int(size), name
     except ValueError:
         raise SCPError(FX_BAD_MESSAGE, 'Invalid copy or dir request') from None
```

**Comment by knkp** [comment] 2020-02-14 03:49
I submitted a pull request a bit ago. Just tested what you put there. And it works!
 👍

**Comment by ronf** [comment] 2020-02-14 03:53
Thanks for reporting this and suggesting a fix! I actually found another similar issue with splitting on colons that I had fixed in one place but not another. I'll have this checked into the "develop" branch shortly.

**Comment by knkp** [comment] 2020-02-14 03:59
No problem, it's exciting just being able to help. 
Glad to see you're still so active on the project!

**Comment by knkp** [comment] 2020-02-14 04:06
By the way this might be an odd question but this is my first time opening an issue on someone else's project. I see this as resolved. Should I close the issue or is that suppose to be done by the maintainer?

**Comment by ronf** [comment] 2020-02-14 04:07
This should now be available in the "develop" branch as commit c992ec4.

**Comment by ronf** [comment] 2020-02-14 04:08
It's up to you, but I'm ok with you leaving this issue open for now. I generally go back and close issues when I actually put out an official release from the master branch with the fix.

**Comment by knkp** [comment] 2020-02-14 04:11
That sounds smart to me. I'll leave it alone. Thanks again.

**Comment by ronf** [comment] 2020-03-01 00:15
This fix is now available in AsyncSSH 2.2.0!

**Closed by ronf** 2020-03-01 00:15 UTC

**Comment by JPrazak** [comment] 2023-04-13 21:54
Hi Ron,
I have similar issue with space in file name, but I use proxy jump.  I tried go through scp.py, but without success. It's failing in _recv_files func. but dstpath is OK with b'' prefix.  
Do you have any idea where the problem should be?
Thank you very much.

```
asyncssh.sftp log  : [conn=10] Starting remote SCP, args: -f /home/admin/dir/part1 end.tar.gz
asyncssh   log  : [conn=10, chan=1] Set write buffer limits: low-water=16384, high-water=65536
asyncssh   log  : [conn=10, chan=1] Requesting new SSH session
asyncssh   log  : [conn=10, chan=1]   Agent forwarding enabled
asyncssh   log  : [conn=10, chan=1]   Command: scp -f /home/admin/dir/part1 end.tar.gz
asyncssh.sftp log  : [conn=10, chan=1] Sending SCP OK
asyncssh.sftp log  : [conn=10, chan=1] Received SCP error: scp: /home/admin/dir/part1: No such file or directory
asyncssh.sftp log  : [conn=10, chan=1] Handling SCP error: scp: /home/admin/dir/part1: No such file or directory
asyncssh.sftp log  : [conn=10, chan=1] Handling SCP error: scp: /home/admin/dir/part1: No such file or directory
asyncssh.sftp log  : [conn=10, chan=1] Stopping remote SCP
asyncssh   log  : [conn=10, chan=1] Closing channel
asyncssh   log  : [conn=10, chan=1] Received exit status 1
asyncssh   log  : [conn=10, chan=1] Received channel close
asyncssh   log  : [conn=10, chan=1] Channel closed
asyncssh   log  : [conn=10] Closing connection
asyncssh   log  : [conn=10] Sending disconnect: Disconnected by application (11)
asyncssh   log  : [conn=9, chan=0] Aborting channel
asyncssh   log  : [conn=10] Connection closed
asyncssh   log  : [conn=9] Closing connection
asyncssh   log  : [conn=9, chan=0] Closing channel
asyncssh   log  : [conn=9] Sending disconnect: Disconnected by application (11)
asyncssh   log  : [conn=9] Connection closed
asyncssh   log  : [conn=9, chan=0] Closing channel due to connection close
asyncssh   log  : [conn=9, chan=0] Channel closed
```

**Comment by ronf** [comment] 2023-04-14 03:56
Keep in mind that the string passed to the remote 'scp' passes through a shell. As such, I think you'll need to quote or backslash-escape spaces, even when using OpenSSH scp on both ends. Also, asterisks and question marks will be treated as wildcards that get expanded on the remote system, and you'd have to backslash-escape those if you had filenames with those characters in them (though that's probably much less likely than spaces).

It might be possible to have AsyncSSH do quoting/escaping automatically for spaces, but that would cause backward compatibility problems with existing code which may already be doing this itself, and there'd still be a need for callers to escape glob characters that you didn't want expanded. So, I'm hesitant to try and change that now.

I think your best bet is to manually add a backslash before any spaces in the remote file paths you pass into scp, or to put them in quotes. For instance:

```python 
    asyncssh.scp("remote_host:/home/admin/dir/part1\\ end.tar.gz", "local_dir")
```

or:

```python 
    asyncssh.scp("remote_host:'/home/admin/dir/part1 end.tar.gz'", "local_dir")
```

In the case of quotes, using single quotes in the remote path is probably safest, as that will also prevent things like dollar-sign substitutions from happening on the remote system, meaning your Python string will probably need to be surrounded by double-quotes, as shown here. For the backslash case, you can use either single or double quotes at the Python level, but you'll need to double the backslash in the strings you specify, again as shown here (or use "raw" strings with an 'r' prefix).

**Comment by JPrazak** [comment] 2023-04-20 16:18
Sorry for late answer. With single quote in remote path it works perfecty.
Thank you for perfect support!

**Comment by ronf** [comment] 2023-04-21 01:00
Glad to hear it - happy to help!
