### ISSUE TITLE
Implement asynchronous context managers

### ISSUE THREAD

**Issue by nchammas** [ronf/asyncssh#41] opened 2016-01-21 13:44 UTC
Just a follow-up to [our discussion on the user list](https://groups.google.com/d/msg/asyncssh-users/ihqdEgV83a0/q7_Edx0KCgAJ) for tracking purposes.

Instead of this:

```python
async def run_client():
    with (await asyncssh.connect('localhost')) as conn:
        chan, session = await conn.create_session(MySSHClientSession, 'ls abc')
        await chan.wait_closed()
```

It would be great if we could say this:

```python
async def run_client():
    async with asyncssh.connect('localhost') as conn:
        chan, session = await conn.create_session(MySSHClientSession, 'ls abc')
        await chan.wait_closed()
```

In other words, let's make the existing connection context managers asynchronous by implementing [`__aenter__()` and `__aexit__()`](https://www.python.org/dev/peps/pep-0492/#asynchronous-context-managers-and-async-with).

I think this can be done in a way that is backwards compatible with Python 3.4, since `__aenter__()` and `__aexit__()` just need to be coroutines and don't have to use the new `async` syntax.

**Comment by ronf** [comment] 2016-01-23 23:54
I took a closer look at this today. Unfortunately, it's trickier than it looks.

To be able to use the async with syntax proposed here, I'd have to have asyncssh.connect() no longer be a coroutine. Instead, it would have to return an object, with that object's __aenter__() function doing what the current connect() coroutine does, eventually returning the SSHConnection object from __aenter__. Unfortunately, that would no longer be backward compatible with the version using with & yield from.

I can make it work by just adding __aenter__/__aexit__, but the syntax is much less pretty. The caller would have to write something like:

```python
async with (await asyncssh.connect('localhost')) as conn:
        chan, session = await conn.create_session(MySSHClientSession, 'ls abc')
        await chan.wait_closed()
```

So far, I don't see a good way to support the new syntax while remaining backward compatible.

**Comment by nchammas** [comment] 2016-01-24 00:07
Oh snap, you're right.

I guess we can either close this or tag it for reconsideration when/if AsyncSSH decides to adopt Python 3.5's `async`/`await` syntax internally and thus break backwards compatibility.

**Comment by ronf** [comment] 2016-01-24 00:36
Yeah - I've been thinking that I'll probably make a "2.0" branch where I require Python 3.5 and begin using the new syntax in the AsyncSSH implementation itself. As part of that, I can also consider some incompatible syntax changes such as this one.

One of the things I'll probably do as part of this is to try and make all callbacks be async. I've been slowing expanding the list of callbacks which can optionally be coroutines in the last few releases (making this optional so I'm still backward compatible with older versions that didn't allow coroutines to be used in those places), but this will be a lot cleaner if I don't need to worry about that and I can use the new syntax.

**Comment by nchammas** [comment] 2016-01-24 00:42
Sounds good to me.

Other context managers that could be updated as part of AsyncSSH 2.0: 
* `SSHClientConnection.start_sftp_client()`

**Comment by ronf** [comment] 2016-06-18 21:24
I spent some time this week looking more closely at this issue, and I've managed to build a wrapper class that lets me support both the Python 3.4 style of non-asynchronous context managers and the newer Python 3.5 async context managers simultaneously, as well as allowing the functions in question to act as normal coroutines using either "yield from" or "await" which return the objects that they do today. As a result, I no longer need to make an incompatible API change to support the new Python 3.5 syntax!

With this new wrapper, I've now enabled async context manager support for SSH connection objects, SFTP client objects, and SFTP file objects, while remaining fully backward-compatible.

The async context managers work basically like the old non-async ones did, automatically closing the object when leaving the context. However, unlike the old version, the async context managers do an implicit wait_closed() on the objects, making sure the objects are fully closed before leaving the block.

I've also updated the documentation and all of the examples to use the new Python 3.5 syntax.

These changes are all now available in the "develop" branch!

**Comment by ronf** [comment] 2016-06-18 22:24
This feature is now released in AsyncSSH 1.5.6.

**Closed by ronf** 2016-06-18 22:24 UTC
Labels: enhancement

**Comment by mjmdavis** [comment] 2024-03-01 02:35
Silly question. How do I keep a long running connection open? It seems that connect only returns the context manager and not a normal connection object that I can keep around.

**Comment by mjmdavis** [comment] 2024-03-01 18:52
Thanks! Did I miss this in the docs? It might be helpful for others if it's not there already or if it was easier to find. I very well may have been a bit dim though.

**Comment by ronf** [comment] 2024-03-02 02:13
The docs indicate that `asyncssh.connect()` is an async function and that it returns an `SSHClientConnection`. There's isn't a specific mention that `SSHClientConnection` objects (among others) can be using as async context managers, but the example code in the documentation makes heavy use of that, and the syntax used is the standard Python syntax for all async context managers (`async with`).

This was also mentioned in the change log when the feature was first added, but it was long enough ago that it doesn't surprise me that you wouldn't have seen that.

**Comment by mjmdavis** [comment] 2024-03-04 17:31
I was thrown by the `_ACMWrapper` return type. I didn't realise / it wasn't clear from the docs that it implemented `__await__` and simply passed through the connection object.

Looking at the [client examples](https://asyncssh.readthedocs.io/en/stable/#client-examples), there isn't an example of using `await asyncssh.connect()`. I also can't find that string by searching the docs.

I would propose adding 2 versions of the the [Simple Client](https://asyncssh.readthedocs.io/en/stable/#simple-client) example. One using a context manager and one using `await asyncssh.connect()`. This is a good place to do so because this is the first place the user is directed after opening the docs.

Why is this a good idea? Because as it stands, the only way to figure this out is to either:
* Read the source code and track down [this line](https://github.com/ronf/asyncssh/blob/21a3062557f334d6183af4946954b0eb6e81aba9/asyncssh/misc.py#L270)
* Find [this page](https://asyncssh.readthedocs.io/en/stable/api.html#asyncssh.connect) in the API documentation.

**Comment by ronf** [comment] 2024-03-06 02:53
I don't really like repeating the initial example on the main page without any explanation for the difference between the two versions. Also, it wouldn't really make sense to use the "await" version in that example, since the connection is used and then immediately closed and there's no good reason to do that manually rather than letting the context manager do it.

That said, there are other cases where it makes sense to use "await", and I'm happy to add some explanatory text about that down in the "examples" section. Take a look at commit a3c3fce for an attempt at this. Feedback is welcome!

**Comment by mjmdavis** [comment] 2024-03-06 05:27
Your example looks great.

I think it would be good to add a short example to the README as well so that people can jump in quickly. Maybe something brief for those that know what they’re looking for. The added detail in the docs is good but I definitely knew what I was looking for and would have figured it out from a short code example.

**Comment by mjmdavis** [comment] 2024-03-11 18:29
I would enocurage making it as clear that both options exist as early as possible. I nearly didn't use this excellent library because of my initial confusion. I also think that there are a lot of use cases for a long lived connection. I ended up spending several hours trying to figure this out and nearly gave up entirely and went back to paramiko which is less well suited to my application.

**Comment by matthew-k2001** [comment] 2024-03-12 03:43
Hi @ronf ,@mjmdavis, I am actually having issueswith sshtunnelling package for my application (fast-api) that requires a long lived connection. Just wanted to get a clarification from you wheather autossh solves this issue. 
Thanks

**Comment by ronf** [comment] 2024-03-12 13:36
The issue being discussed here is not really about "long lived" connections. AsyncSSH has no problem with that. The issue was about when it was appropriate to use a context manager, which by design closes the connection when the program exits the code block the context manager was created for. If you want to open a connection and return that connection object to calling code, you need to use "await" instead of "async with". This is standard behavior for all context managers, and is not specific to AsyncSSH.

The "autossh" program solves a different problem, which has to do with reconnecting an SSH connection if it breaks. It appears to be written in C and uses OpenSSH. It has nothing to do with AsyncSSH, asyncio, or Python. If you did want to have AsyncSSH reconnect automatically when an SSH connection broke, it wouldn't be too difficult to do that, but you'd have to code this yourself. This isn't a built-in feature of AsyncSSH (just like it isn't a feature of OpenSSH).

**Comment by matthew-k2001** [comment] 2024-03-13 01:29
Thanks @ronf for the detailed reply. Silly question here but is it possible to programmatically handle the "autossh" by checking whether the tunnel is still alive, by testing the connection ?

**Comment by ronf** [comment] 2024-03-13 05:36
Yes - you could either catch the exception when you tried to open a new session on a connection that had broken, or you could implement a subclass of SSHClient so that you could act when you received the `connection_lost()` callback, closing the previous connection and then opening a new one if you wanted to always make sure that a live connection was available.

There are some edge cases here to worry about, of course. The attempt to re-open the connection might fail, for instance. Also, you may get requests for new sessions while the connection is still being established, so you might have to queue some of those up and then attempt to open those sessions after the connection establishment completes (if it succeeds).

**Comment by matthew-k2001** [comment] 2024-03-13 05:46
Thanks @ronf that makes sense !
