### ISSUE TITLE
setup.py test results on 1.14.0

### ISSUE THREAD

**Issue by ndowens** [ronf/asyncssh#165] opened 2018-09-10 02:01 UTC
FAIL: test_get_not_permitted (tests.test_sftp._TestSCP)
Test getting a file with no read permissions over SCP
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/poudriere/ports/head/security/py-asyncssh/work-py36/asyncssh-1.14.0/tests/util.py", line 77, in async_wrapper
    return self.loop.run_until_complete(wrapped_func)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/poudriere/ports/head/security/py-asyncssh/work-py36/asyncssh-1.14.0/tests/test_sftp.py", line 2798, in test_get_not_permitted
    yield from scp((self._scp_server, 'src'), 'dst')
AssertionError: SFTPError not raised

======================================================================
FAIL: test_get_not_permitted (tests.test_sftp._TestSCPAsync)
Test getting a file with no read permissions over SCP
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/poudriere/ports/head/security/py-asyncssh/work-py36/asyncssh-1.14.0/tests/util.py", line 77, in async_wrapper
    return self.loop.run_until_complete(wrapped_func)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/poudriere/ports/head/security/py-asyncssh/work-py36/asyncssh-1.14.0/tests/test_sftp.py", line 2798, in test_get_not_permitted
    yield from scp((self._scp_server, 'src'), 'dst')
AssertionError: SFTPError not raised

======================================================================
FAIL: test_open_read_not_permitted (tests.test_sftp._TestSFTP)
Test reading data from a file with no read permission
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/poudriere/ports/head/security/py-asyncssh/work-py36/asyncssh-1.14.0/tests/util.py", line 77, in async_wrapper
    return self.loop.run_until_complete(wrapped_func)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/poudriere/ports/head/security/py-asyncssh/work-py36/asyncssh-1.14.0/tests/test_sftp.py", line 77, in sftp_wrapper
    yield from asyncio.coroutine(func)(self, sftp)
  File "/usr/local/poudriere/ports/head/security/py-asyncssh/work-py36/asyncssh-1.14.0/tests/test_sftp.py", line 1342, in test_open_read_not_permitted
    f = yield from sftp.open('file')
AssertionError: SFTPError not raised

======================================================================
FAIL: test_open_read_not_permitted (tests.test_sftp._TestSFTPAsync)
Test reading data from a file with no read permission
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/poudriere/ports/head/security/py-asyncssh/work-py36/asyncssh-1.14.0/tests/util.py", line 77, in async_wrapper
    return self.loop.run_until_complete(wrapped_func)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/poudriere/ports/head/security/py-asyncssh/work-py36/asyncssh-1.14.0/tests/test_sftp.py", line 77, in sftp_wrapper
    yield from asyncio.coroutine(func)(self, sftp)
  File "/usr/local/poudriere/ports/head/security/py-asyncssh/work-py36/asyncssh-1.14.0/tests/test_sftp.py", line 1342, in test_open_read_not_permitted
    f = yield from sftp.open('file')
AssertionError: SFTPError not raised

**Comment by ronf** [comment] 2018-09-10 02:41
I'm not seeing these failures here, or either MacOS or Ubuntu. It's also not showing up on TravisCI or AppVeyor, on any of Linux, Mac, and Windows. Which platform are you seeing this on?

Do you get this same set of errors from earlier AsyncSSH releases?

**Comment by ndowens** [comment] 2018-09-10 02:49
@ronf yep on 1.12.1 as well

**Comment by ndowens** [comment] 2018-09-10 02:49
freebsd

**Comment by ronf** [comment] 2018-09-10 03:04
Ok, so it isn't new, but it does seem to be specific to FreeBSD (and maybe other BSD flavors). Unfortunately, I don't have any BSD machines here to test this against. Could you do a bit more digging into the specific tests? They all seem to be related to permissions, so that's probably the place to start. There's really only two tests here -- you're just seeing each of these run twice, once synchronously and once asynchronously.

The specific tests are both quite short:

```python
            self._create_file('file', mode=0)

            with self.assertRaises(SFTPError):
                f = yield from sftp.open('file')
```

and

```python
            self._create_file('src', mode=0)

            with self.assertRaises(SFTPError):
                yield from scp((self._scp_server, 'src'), 'dst')
```

I suspect it has to do with the use of "mode=0" in the create_file function, which turns into:

```python
        if mode is not None:
            os.chmod(name, mode)
```

Perhaps FreeBSD doesn't like chmod() being called with a mode of 0? It seems to be that should be allowed. Can you try and repeat this with a standalone program, such as:

```python
import asyncio, asyncssh, os, sys

async def run_client():
    with open('/tmp/example.txt', 'w') as f:
        f.write('test')

    os.chmod('/tmp/example.txt', 0)

    await asyncssh.scp('localhost:/tmp/example.txt', '/tmp')

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SFTP operation failed: ' + str(exc))
```

You should see an error such as:

    SFTP operation failed: [Errno 13] Permission denied: '/tmp/example.txt'

**Comment by ronf** [comment] 2018-09-10 03:26
If you have a copy of the asyncssh tar file unpacked you can put this example in the same directory as the setup.py.

**Comment by ndowens** [comment] 2018-09-10 03:32
SFTP operation failed: Disconnect Error: No trusted server host keys available

**Comment by ronf** [comment] 2018-09-10 03:50
You'll need a trusted key for localhost in your .ssh/known_hosts file. You should be able to get that if you just "ssh localhost" by hand and tell it to add the key.

**Comment by ndowens** [comment] 2018-09-10 04:00
SFTP operation failed: Disconnect Error: Permission denied

**Comment by ronf** [comment] 2018-09-10 04:02
That's closer, but that suggests you are getting the error on the remote system, not the local one, which doesn't seem right here. Try changing the line:

    await asyncssh.scp('localhost:/tmp/example.txt', '/tmp')

to:

    await asyncssh.scp('localhost:/tmp/example.txt', '/tmp/example2.txt')

**Comment by ndowens** [comment] 2018-09-10 04:06
SFTP operation failed: [Errno 13] Permission denied: '/tmp/example.txt'

**Comment by ronf** [comment] 2018-09-10 04:12
Ok, so you're able to reproduce the expected error. Given that, I'm not really sure why the tests are failing. They're doing something very similar.

**Comment by ronf** [comment] 2018-09-10 05:10
I just had a friend run this on FreeBSD 11.1-STABLE #0 r32705, and all tests passed. So, the issue seems specific to your environment.

**Comment by drosehn** [comment] 2018-09-10 17:40
I'm not completely sure how all these pieces fit together, but note that the error messages say things like:

> File "/usr/local/poudriere/ports/head/security/py-asyncssh/work-**py36**/asyncssh-1.14.0/tests/util.py", line 77, in async_wrapper

> File "/usr/local/lib/**python3.6**/asyncio/base_events.py", line 468, in run_until_complete

> File "/usr/local/poudriere/ports/head/security/py-asyncssh/work-**py36**/asyncssh-1.14.0/tests/test_sftp.py", line 2798, in test_get_not_permitted

Which suggests python 3.6 instead of python 3.5.  Might it be that you're getting some mixture of the two versions?

Also this suggests you're building AsyncSSH via poudriere.  I don't happen to use poudriere, so I don't know how that effects testing.

**Comment by ronf** [comment] 2018-09-11 00:51
AsyncSSH itself should work fine on all flavors of 3.4, 3.5, 3.6, and 3.7. The code is the same for all of them, with just an occasional run-time check to deal with minor differences in Python 3.5.2 and earlier. So, I don't think the version should be causing a problem for AsyncSSH, but if you were somehow running a 3.5 Python binary with a 3.6 library, I'm not sure what would happen in the Python code itself. Are you sure you weren't running 3.6 here?

**Comment by ronf** [comment] 2018-09-11 01:41
Ok - in a previous post, you mentioned 3.5.

**Comment by ndowens** [comment] 2018-09-11 03:47
ah sorry, I was going through py version until i remembered the module needed for this pkg was installed for py36

**Comment by ronf** [comment] 2018-09-16 01:50
I managed to get access to a FreeBSD system today, and I may have reproduced this!

It turns out that FreeBSD has a problem with trying to set the sticky bit on a plain file, which is allowed on Linux and many other UNIXes, even though it is a no-op. I've reworked my test and checked in a potential fix in commit 4b3dec9 in the "develop" branch, if you'd like to give it a try.

**Comment by ndowens** [comment] 2018-09-16 02:36
Thanks @ronf I will give it a try ASAP

**Comment by ndowens** [comment] 2018-09-16 15:50
Well tried it and got the same error as before

**Comment by ronf** [comment] 2018-09-16 16:44
Ok - the error case I fixed was similar to the ones you reported, but not exactly the same, so I'm not too surprised. With the changes I made, all the tests ran perfectly on three different versions of FreeBSD, though, and I also had someone else try it and it ran fine for them on FreeBSD. So, there's something different in your test environment.

**Comment by ndowens** [comment] 2018-09-16 20:34
Yea not sure. I tested it in a FreeBSD jail and also on host machine it's self

**Comment by ronf** [comment] 2018-09-19 04:13
Is there anything special about /tmp on the machine you are testing on? In particular, is there anything that might make your system not enforce file permissions in directories under /tmp?

**Comment by ndowens** [comment] 2018-09-19 04:32
Haven't changed any dirs permissions or anything; they are all default

**Comment by ronf** [comment] 2019-05-18 14:50
Since I haven't been able to reproduce this on multiple FreeBSD systems, I'm going to close this for now. Feel free to re-open it or file a new issue if you get any more information about it.

**Closed by ronf** 2019-05-18 14:50 UTC
