### ISSUE TITLE
issue with sudo

### ISSUE THREAD

**Issue by alexk2000** [ronf/asyncssh#191] opened 2019-02-01 14:18 UTC
Hello,

Could you please help me to understand how to run remote commands via sudo.
SSH keys configured and I am able to run this without entering password:

ssh <user>@<host> '/bin/sudo /bin/id'
uid=0(root) gid=0(root) groups=0(root)

When I am trying AsyncSSH:

import asyncio, asyncssh, sys

async def run_client():
    async with asyncssh.connect(host='<host>', username='<user>') as conn:
        result = await conn.run('/bin/sudo /bin/id',
                                term_type='xterm-color',
                                term_size=(80, 24),
                                env={'LANG': 'en_GB', 'LC_COLLATE': 'C'})
        print(result.stdout, end='')

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))

I am getting delay and exiting with output:
[sudo] password for <user>

Python 3.6.5
asyncssh 1.15.1

**Comment by ronf** [comment] 2019-02-02 04:45
I think your problem here is the use of `username=''`. Note that it's prompting for "[sudo] password for" with an empty username.

When I try running the regular SSH command with just '@' as the user/host as you show here, I get back the SSH usage text. The same goes when I try to use something like '@localhost'. It requires that I provide a non-empty username before it will try to connect.

When I do something similar using `username=''` in AsyncSSH, the server I'm trying to connect to fails to authenticate the empty username, which is expected.

What type of SSH server are you connecting to? Is it some kind of embedded SSH that doesn't actually have usernames/passwords set on it?

**Comment by alexk2000** [comment] 2019-02-02 07:39
Sorry for this misunderstanding, I specified user as `<user>` and host as `<host>` but it's remove by Github.

**Comment by alexk2000** [comment] 2019-02-02 07:45
This is like this:
`ssh <user>@<host> '/bin/sudo /bin/id'
uid=0(root) gid=0(root) groups=0(root)`

`import asyncio, asyncssh, sys

async def run_client():
    async with asyncssh.connect(host=<host>, username=<user>) as conn:
        result = await conn.run('/bin/sudo /bin/id',
                                term_type='xterm-color',
                                term_size=(80, 24),
                                env={'LANG': 'en_GB', 'LC_COLLATE': 'C'})
        print(result.stdout, end='')

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc)`

This code works fine  if I run any other command without sudo

**Comment by ronf** [comment] 2019-02-02 15:35
Ah, yeah - when you paste code, you generally want to use the "Insert code" button in editor here to wrap around the block so that it preserves indentation and special characters like that.

Are you doing anything to feed the user's password to sudo? If not, it will wait for you to enter that and may eventually time out like you saw if no password is provided. This password challenge will not automatically be passed through to the local terminal on the system running the script.

To avoid hardcoding the user's password into the script, you'd need to interactively prompt the local user for the password explicitly and feed it into the command through the SSH session's stdin at the right time, assuming you don't want to make the remote account privileged enough to run "sudo" without providing a password. You'd also need to be careful about not asking for it and sending it unless "sudo" prompts for it. If you do, you might expose the password as input to something else.

**Comment by alexk2000** [comment] 2019-02-02 16:51
sudo on remote host configured for this user to run without asking password:
some_user ALL=(ALL) NOPASSWD: ALL

To verify this I run

ssh some_user@some_host '/bin/sudo /bin/id'

and got 

uid=0(root) gid=0(root) groups=0(root)

Without asking the password. So I am able to run any command as root via sudo on remote host using ssh command. But this doesn't work when using AsyncSSH code above. 
Does this case work for you (sudo without password)?

**Comment by ronf** [comment] 2019-02-02 22:52
Unfortunately, I can't reproduce this here on either MacOS or Linux in the case where NOPASSWD is set as you've described. Without that, I get the hang you described though, and I originally mentioned the password prompt as a potential issue since your first post showed that when it finally exited it appeared to have output such a prompt.

**Comment by ronf** [comment] 2019-05-18 15:01
Closing this for now, as I can only reproduce it in cases where the remote system prompts for password and a hang/delay is expected in that case. If you have any additional information, feel free to reopen this or create a new issue.

**Closed by ronf** 2019-05-18 15:01 UTC
