### ISSUE TITLE
exit_status is not updated?

### ISSUE THREAD

**Issue by haizaar** [ronf/asyncssh#147] opened 2018-05-25 08:06 UTC
Good time of a day Ron,

From time to time I observe a behavior, where the spawned process finishes, but its `exit_status` field is still None and not get updated.  I happens once in several hundred spawns. 

Here is the reproduction:

```python
import asyncssh

async def run_raw():
    cmd = "for i in {1..100}; do echo $i 1234567890; done"
    ssh = await asyncssh.connect(host="localhost")
    for i in range(1000):
        async with ssh.create_process(cmd, term_type="xterm-color") as process:
            while process.exit_status is None:
                line = await process.stdout.readline()
                print("Line:", repr(line), bool(line))

asyncio.get_event_loop().run_until_complete(run_raw())
```

It never managed to complete the 1000 iterations in the loop - Eventually it hits the condition where `process.exit_status` remains `None` and the program keeps printing empty lines.

Is it a bug or am I missing something?

Best,
Zaar

**Comment by ronf** [comment] 2018-05-26 02:47
Hi Zaar,

I believe what you're seeing here is a race on the server between sending EOF and sending the exit status. Generally speaking, EOF is sent on stdout first and the exit status comes as a separate message after that. If there's enough time between these two events, your call to readline() could return an empty string indicating that it got EOF, but the process.exit_status would still not be filled in until later. This could cause a bunch of consecutive empty strings to be returned from readline() as far as you can call that, until finally the message sending the exit status arrives and causes you to drop out of the loop.

Since you are using readline() in this particular example, the simplest approach to address this is to take advantage of the fact that process.stdout is an async iterator which returns one line at a time of the output and write something like:

```python
async def run_raw():
    cmd = "for i in {1..100}; do echo $i 1234567890; done"
    ssh = await asyncssh.connect(host="localhost")
    for i in range(1000):
        async with ssh.create_process(cmd, term_type="xterm-color") as process:
            async for line in process.stdout:
                print("Line:", repr(line), bool(line))
```

If you wanted to do other forms of reading in the loop, you'd probably want to test if the return value from the read calls is the empty string and break out of the loop when it is. Getting back empty string from a read is how you know you are at EOF. There's also an at_eof() function you can call, but that would still potentially suffer from a race condition where at_eof() returns that you're not yet at EOF, but a later read returns the empty string when the EOF message arrives.

If you are seeing it sit there looping returning the empty string, that suggests that something happened which caused your SSH server to never get around to sending the exit status message. I haven't been able to reproduce that here, but the above suggestions should prevent a missing exit status like that from causing you a problem exiting the read loop.

**Comment by haizaar** [comment] 2018-05-28 02:54
Hi Ron,

Thanks for suggestion about async generator, though in real code readline() is wrapped with asyncio.timeout(), so I guess I'll stick with checking for empty response from readline(), which works great.

It's behaving exactly as you describe - sometime it prints several dozens or hundreds of empty lines and then process.exit_status is finally updated. This is quite clear and reasonable.

What's interesting is that from time time to time, exist_status does not seem to be updated at all - a script can print empty lines **for minutes** until I kill it. It's even more interesting that you can't reproduce it. For me it happens regularly with a bunch of remote OpenSSH servers on Ubuntu 16.04 and Centos 6.2; and client scripts running on Ubuntu 16.04 and Debian Jessie. I'm using the latest asyncssh 1.13.0, though I happened on 1.12.x as well.
I've enabled logging, and noticed that "Received exit status..." is indeed missing when the above circumstances happen.

P.S. I see that the above logging line is defined in channel.py:_process_exit_status_request() function, but I don't see this function called anywhere (though according the the logs, it is). I'm curious how does it work.

P.P.S. May I ask why did you use your own asn1 implementation instead of pyasn1?

**Comment by ronf** [comment] 2018-05-28 17:30
The fact that you didn't see the "Received exit status" log message indicates pretty strongly that this is  an issue on the server, though it's not clear what causes it.

If you set the AsyncSSH debug level to 3, you'll be able to see the raw SSH messages being sent and received, and you could try to see whether or not there are any differences in message ordering from the AsyncSSH client or the server that might give you a clue why the server sends the exit status in some cases but not others before it closes the channel.

Regarding _process_exit_status_request, the method name is computed dynamically in SSHChannel:

```python
    def _service_next_request(self):
        """Process next item on channel request queue"""

        request, packet, _ = self._request_queue[0]

        name = '_process_' + map_handler_name(request) + '_request'
        handler = getattr(self, name, None)

        if callable(handler):
            result = handler(packet)
        else:
            self.logger.debug1('Received unknown channel request: %s', request)
            result = False

        if result is not None:
            self._report_response(result)
```

This makes it really easy for me to add handlers for new channel requests by their name. All I need to do is define a method on the class which follows the right naming convention.

Regarding PyASN1, the main issue was code size and simplicity. In total, PyASN1 was something like 18,000 lines of code. I think the initial implementation I wrote was about 500 lines, and even after expanding my version to support what I needed to parse X.509 certificates, I'm still under 1000 lines (including unit tests). I have nothing against PyASN1 -- it's got some very nice functionality. It was just more than I needed. At the time I made the decision, I think PyASN1 was bigger than all of AsyncSSH, or at least comparable in size.

**Comment by haizaar** [comment] 2018-05-29 03:30
Thanks for the great info, as usual :)

Since there is a perfectly functioning workaround, I will try to debug this later on when I have time.

**Comment by ronf** [comment] 2018-05-29 03:49
Yup - glad to hear that testing for the empty string is working for you. Let me know if there's anything else I can help with.

**Comment by ronf** [comment] 2018-07-11 02:58
Closing this for now - feel free to reopen it or open a new issue if you get more information, or if you are able to come up with a test case where you can reproduce this problem.

**Closed by ronf** 2018-07-11 02:58 UTC
