### ISSUE TITLE
Incorrect mac received on packet

### ISSUE THREAD

**Issue by ghost** [ronf/asyncssh#343] opened 2021-01-25 02:31 UTC
I'm getting an error on putty and it says 'Incorrect MAC received on packet' when I type a lot in the asyncssh server.

Any ideas?

**Comment by ronf** [comment] 2021-01-25 04:03
Sorry, that's not nearly enough information to go on. The error just means that there was something wrong with the data received. It could be caused by many different things. Under what conditions does this happen, and how repeatable is it? Do you have sample code which exhibits the problem?

Since you mention PuTTY here, I'm guessing that AsyncSSH is being used as the server. Do you have any debug logs from AsyncSSH when this happens?

**Comment by LightTheSylveon** [comment] 2021-01-25 09:11
Theres no debug logs somehow, it occurs when I spam the asyncssh server for a longer amount of time, but it mostly random. It can happen when I just press enter, or type a letter too

**Comment by ronf** [comment] 2021-01-26 01:25
AsyncSSH wouldn't care at all about color. Those are just escape sequences sent in the data that it doesn't look at.

There's no logging enabled by default, but you if you set the log level explicitly to DEBUG, you should begin seeing this output from the AsyncSSH server process. You'd probably want to increase the debug level to 2 in this case, to get more detail. The calls would look something like:

```python
import logging

logging.basicConfig()
asyncssh.set_log_level('DEBUG')
asyncssh.set_debug_level(2)
```

These calls should be made before doing the asyncssh.create_server() or asyncssh.listen() call.

**Comment by LightTheSylveon** [comment] 2021-01-26 09:01
I did that, and it didnt show anything.

**Comment by ronf** [comment] 2021-01-28 04:19
If you're not seeing any log output at all, that suggests that you aren't actually receiving any connections to your AsyncSSH server's listener. Assuming logging is enabled, I don't see any other way you'd get no output.

Kind of a long shot but did you leave out the port number on your client, such that you're connecting to the default SSH server on the system instead?

**Comment by LightTheSylveon** [comment] 2021-01-28 08:03
I meant im getting no output when the "incorrect MAC received on packet" occurs, it does show everything else like connectiom details, received and sending, and all the other debug stuff.

**Comment by ronf** [comment] 2021-01-29 02:26
Ah, I see. It wouldn't necessary log anything specific related to the error, but if you could see what the last type of packet it sent before the connection was closed and confirm that the close was initiated by the client and not the server, that might tell us something, particularly if the pattern was consistent about what the last thing output was.

**Comment by LightTheSylveon** [comment] 2021-01-29 07:38
DEBUG:asyncssh:[conn=0, chan=0] Sending 1 data byte
INFO:asyncssh:[conn=0, chan=0] Closing channel due to connection close
INFO:asyncssh:[conn=0, chan=0] Channel closed: [Errno 104] Connection reset by peer
[+] Disconnection
[!] Error on [Errno 104] Connection reset by peer
INFO:asyncssh:[conn=0, chan=0] Closing channel

**Comment by ronf** [comment] 2021-01-30 15:10
Ok - there's nothing unusual looking in the debug output here. It just looks like the connection broke at the TCP level. One possible explanation for this would be if there was a firewall in between that lost state about the connection and stopped letting the traffic through. This can happen if the connection goes idle for an extended period of time, or just if the firewall is rebooted or has its connection table overflow. Could something like that be happening here?

If that's the cause, enabling keepalive requests on the connection can sometimes help.

**Comment by ronf** [comment] 2021-01-30 15:12
On - one other thought. Is there any chance the remote system you are accessing is rebooting? That would be another possible explanation for an unexpected TCP connection drop.

It could also be caused by a temporary network outage, if it lasts long enough.

**Comment by LightTheSylveon** [comment] 2021-01-30 21:56
> Ok - there's nothing unusual looking in the debug output here. It just looks like the connection broke at the TCP level. One possible explanation for this would be if there was a firewall in between that lost state about the connection and stopped letting the traffic through. This can happen if the connection goes idle for an extended period of time, or just if the firewall is rebooted or has its connection table overflow. Could something like that be happening here?
> 
> If that's the cause, enabling keepalive requests on the connection can sometimes help.

How do I enable keepalive requests?

**Comment by LightTheSylveon** [comment] 2021-01-30 21:57
> On - one other thought. Is there any chance the remote system you are accessing is rebooting? That would be another possible explanation for an unexpected TCP connection drop.
> 
> It could also be caused by a temporary network outage, if it lasts long enough.

No its definitely not rebooting

**Comment by ronf** [comment] 2021-01-30 22:01
When making the connection, set the “keepalive_interval” to how often you want to send a keep alive message. A reasonable value is something like 1-5 minutes. This can either be express as an integer in seconds (e.g. 300 for 5 minutes), or you can pass a string like ‘5m’.

**Comment by LightTheSylveon** [comment] 2021-01-30 22:03
> When making the connection, set the “keepalive_interval” to how often you want to send a keep alive message. A reasonable value is something like 1-5 minutes. This can either be express as an integer in seconds (e.g. 300 for 5 minutes), or you can pass a string like ‘5m’.

Sure thanks I will try this tomorrow.

**Comment by LightTheSylveon** [comment] 2021-02-01 11:12
> 
> 
> When making the connection, set the “keepalive_interval” to how often you want to send a keep alive message. A reasonable value is something like 1-5 minutes. This can either be express as an integer in seconds (e.g. 300 for 5 minutes), or you can pass a string like ‘5m’.

What do I use keepalive_interval() on?

'SSHServerProcess' object has no attribute 'keepalive_interval'

I tried it on this.

**Comment by ronf** [comment] 2021-02-01 15:12
It's at the connection level, so you'd use it in your call to listen() or create_server().

**Comment by LightTheSylveon** [comment] 2021-02-01 17:28
> 
> 
> It's at the connection level, so you'd use it in your call to listen() or create_server().

It didn't fix the issue, im still getting the same issue.

**Comment by ronf** [comment] 2021-02-02 02:27
Ok. If you try out different encryption algorithms, does that make any difference? Basically, PuTTY is telling you it doesn't like something AsyncSSH is sending and that's triggering a connection close, but I've never seen anyone else report anything like this (at least not in a very long time). On the AsyncSSH side, it's seeing the connection drop and doing its standard cleanup. So, there's no new information there. Either you're tickling a bug in PuTTY or in AsyncSSH that's causing one of them to calculate the MAC wrong, or something is corrupting the bytes going out on the connection (like by writing directly to the transport, bypassing AsyncSSH).

**Comment by LightTheSylveon** [comment] 2021-02-02 14:06
> 
> 
> Ok. If you try out different encryption algorithms, does that make any difference? Basically, PuTTY is telling you it doesn't like something AsyncSSH is sending and that's triggering a connection close, but I've never seen anyone else report anything like this (at least not in a very long time). On the AsyncSSH side, it's seeing the connection drop and doing its standard cleanup. So, there's no new information there. Either you're tickling a bug in PuTTY or in AsyncSSH that's causing one of them to calculate the MAC wrong, or something is corrupting the bytes going out on the connection (like by writing directly to the transport, bypassing AsyncSSH).

I tried to do exactly that, I tried limiting it to just using Xchacha, and using sha256-(something), anyway, I tried a lot of them just seperately and it didn't work out, I got the same bug

**Comment by ronf** [comment] 2021-02-07 18:09
Ok.

Unfortunately, I'm not sure what else to suggest. Do you think you'd be able to generate a small test program that demonstrates the problem? If I could reproduce it here, I could do some deeper debugging on it to see exactly what kind of corruption might be occurring.

**Comment by LightTheSylveon** [comment] 2021-02-10 10:28
Sure! Ill get to it in a minute!

**Comment by ronf** [comment] 2021-09-06 21:35
Closing due to inactivity. Please open a new issue if you have additional questions.

**Closed by ronf** 2021-09-06 21:35 UTC
