### ISSUE TITLE
Add basic tests for server and client

### ISSUE THREAD

**Issue by nchammas** [ronf/asyncssh#22] opened 2015-06-18 17:50 UTC
Since this project implements both SSH server and client, it would be great if for starters we had some simple tests that just spun up both a server and client and had them interact in some way.

We could probably even add a test that spins up 1000 clients for 1 server and confirms that they can all run some simple command "quickly".

Adding some tests like these would give contributors a simple framework for adding more such tests and would give us some good test coverage.

**Comment by ronf** [comment] 2015-06-21 00:08
Now that I've finished doing the pylint cleanups, filling in more unit tests in next on my list. I'm going to start with doing some individual module testing, but I would like to also include the kind of tests you're talking about here that exercise the full client and server.

That said, I would like whenever possible to test against another SSH implementation here rather than testing my own client & server against one another. That way, I'll see interoperability issues that I might not otherwise if my client & server are non-standard but work correctly with one another. I can probably include both forms of the test, though, one with a third party client or server taking to my code and another where I test against myself.

Today I checked in a set of tests for my ASN.1 module, and fixed a handful of issues they uncovered. I confirmed that I have 100% code coverage of that module with these new tests. Next I'm planning to look into getting more complete code coverage on the key import/export tests I checked in a while ago.

**Comment by nchammas** [comment] 2015-12-05 21:38
By the way, when we have a good set of tests checked in (and I think we do now, right?), we'll be able to start testing AsyncSSH on a continuous basis using [Travis](https://travis-ci.org/) (for Linux) and [AppVeyor](http://www.appveyor.com/) (for Windows).

**Comment by ronf** [comment] 2015-12-10 06:09
I'm still working on getting tests in place. I have most of the utility modules covered pretty well now, but am just starting to write tests for the public API calls and the main classes like connection and channel and haven't checked those in yet. Once I have good coverage there, I'll definitely be looking into getting something like Travis working here.

**Comment by ronf** [comment] 2016-06-07 03:16
It's been a while since I've updated this issue, but I'm happy to say that I just released AsyncSSH 1.5.4 and it is now up to 100% code coverage under unit testing for all modules!

When I get a chance, I'll see if I can get Travis set up on it as well.

**Comment by ronf** [comment] 2016-06-08 06:02
Ok - I have unit testing now running under Travis CI. I'm currently testing Python 3.4 and 3.5 on Linux and the latest Python 3 from "brew" on OS X.

I also have a Linux "nightly" Python 3.6-dev build, but I have that marked to allow errors for now as there seems to be some kind of intermittent issue with networking there, causing a bunch of the tests to fail with "Network is unreachable" errors.

**Closed by ronf** 2016-06-08 06:02 UTC
Labels: enhancement
