### ISSUE TITLE
test_expired_root fails on Python 3.10

### ISSUE THREAD

**Issue by gsauthof** [ronf/asyncssh#326] opened 2020-11-19 11:36 UTC
A Fedora developer re-built all Python packages against a Python 3.10 pre-release version and reported an asyncssh issue (i.e. with asyncssh 2.4.2):

```
======================================================================
FAIL: test_expired_root (tests.test_x509._TestX509)
Test failed validation of expired X.509 root CA
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/asyncssh-2.4.2/tests/test_x509.py", line 211, in test_expired_root
    cert.validate([int_ca, root_ca], None, None, None)
AssertionError: ValueError not raised
----------------------------------------------------------------------
```

The Fedora ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1899474

Of course, could also be caused by some regression inside Python 3.10 itself, as well.

**Comment by ronf** [comment] 2020-11-20 07:15
Thanks for the report!

I just tested this on the Mac with AsyncSSH 2.4.2 on python 3.10.0a2 with cryptography 3.2.1, and pyOpenSSL 19.1.0 and wasn't able to reproduce it. When I get a chance, I'll try and see if I can get it to work in Fedora.

**Comment by ronf** [comment] 2020-11-21 04:28
Ok - I've been able to reproduce this on Fedora release 33 with Python 3.9. However, the exact same test worked fine on Ubuntu 20.04 with Python 3.9. Digging a bit further, I noticed the versions of cryptography were different on the two systems. Experimenting a bit, I found that I could reproduce the problem on Ubuntu with cryptography 3.1.1 or later, but not earlier releases. This seemed to hold on Fedora as well.

In terms of Python versions, I see the same issue on 3.8 depending on which version of cryptography I have installed, so it seems like something might have gotten broken between 3.1 and 3.1.1.

That said, I can't explain my earlier success with Python 3.10a2 on the Mac with cryptography 3.2.1. When I went and tried it again just now, it failed. So, whatever the error is might not be 100% reproducible. Perhaps it depends on the specific time the test is run. I'm going to see if I can find any changes between cryptography 3.1 and 3.1.1 which might be relevant.

**Comment by ronf** [comment] 2020-11-21 04:54
One difference between cryptography 3.1 and 3.1.1 is the version of OpenSSL it linked against. On a few different platforms I checked, cryptography 3.1 linked against OpenSSL 1.1.1g from 21 Apr 2020, while 3.1.1 linked against OpenSSL 1.1.1h from 22 Sep 2020. It's possible that's the source of the issue here, as the certificate validation is going through pyOpenSSL 19.1.0 in all cases, and I think that's a pretty thin layer on top of the direct OpenSSL API.

**Comment by ronf** [comment] 2020-11-21 05:26
Here's a test case I just put together for this issue which depends only on pyOpenSSL:

```python
from OpenSSL import crypto

root = crypto.load_certificate(crypto.FILETYPE_PEM, """
-----BEGIN CERTIFICATE-----
MIIC0jCCAbqgAwIBAgIUJH0cWAbl93Ro9NvyMkiZOc0DJKUwDQYJKoZIhvcNAQEL
BQAwDzENMAsGA1UECwwEcm9vdDAeFw03MDAxMDEwMDAwMDBaFw0yMDExMjEwNTA4
NDRaMA8xDTALBgNVBAsMBHJvb3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC+X7jHYBS1olehAZl5tYg9+/uyEBmdHnh2nbKZounOe0iAdBIErOrX237y
4sAv0LxjWQqLIsiPT43eXncEBbb8am1qOVwBazn/4/DejEnLKLLRNFU5vdGCquhm
PiO+TCAUnERE2lTRIm9Wo4qm2psfVZhM0Wxed8bnD5IoR7kmJlVrJA8kggXARvcZ
Uhk/X3jzbu7xnkNOgszYkY5xZ+MH5wuvBM8RJOQO3XMIHcKkl0pxZFYmzJFWrZuu
SCOdO6PjstHLQi8XDBZbRNaYBecJMFo+sdvHQUX0deIGEzUBj6AkwoyQN8rmWZYT
ibAwdFhL9TmaDXqGKupscN+9Hz0/AgMBAAGjJjAkMBIGA1UdEwEB/wQIMAYBAf8C
AQEwDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3DQEBCwUAA4IBAQCD8xtGEgtZO5Wm
vWpjqyfd87iLRjHrpIXCr9wZ9wqxSG2YON6aWoq6wwvHCQZqKQh5G3RhqTzY/pye
PFTg+5FhmylEgKgTNN84DDJmeoAF+f8Za/29+AKF1HbtY5r8weWlSN2veiKYTxe2
gfjh/UpPMG0lnm8lX93R+VXrbHEN67HJc2/V+9Yx40fbGD2Lu25/jOlrw4A2JGqw
iozjFSem/jGpA/s4834AAkUk7dPRRQJWXyuAHCUZjczFKOtfQHCTpMx23W1ZImwI
287rvGUr58ra1d3FOL7zD3x53hWSYlHe8r55osc5DdZpdXC2rY+d1ZPY6GAp4Mar
oy0wpVWM
-----END CERTIFICATE-----""")

cert = crypto.load_certificate(crypto.FILETYPE_PEM, """
-----BEGIN CERTIFICATE-----
MIICzjCCAbagAwIBAgIUPb4cvqW+x9ChDyGPYTbhrLlJbR8wDQYJKoZIhvcNAQEL
BQAwDzENMAsGA1UECwwEcm9vdDAgFw03MDAxMDEwMDAwMDBaGA85OTk5MTIzMTIz
NTk1OVowDzENMAsGA1UECwwEdXNlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAL5fuMdgFLWiV6EBmXm1iD37+7IQGZ0eeHadspmi6c57SIB0EgSs6tfb
fvLiwC/QvGNZCosiyI9Pjd5edwQFtvxqbWo5XAFrOf/j8N6MScsostE0VTm90YKq
6GY+I75MIBScRETaVNEib1ajiqbamx9VmEzRbF53xucPkihHuSYmVWskDySCBcBG
9xlSGT9fePNu7vGeQ06CzNiRjnFn4wfnC68EzxEk5A7dcwgdwqSXSnFkVibMkVat
m65II507o+Oy0ctCLxcMFltE1pgF5wkwWj6x28dBRfR14gYTNQGPoCTCjJA3yuZZ
lhOJsDB0WEv1OZoNeoYq6mxw370fPT8CAwEAAaMgMB4wDAYDVR0TAQH/BAIwADAO
BgNVHQ8BAf8EBAMCA6gwDQYJKoZIhvcNAQELBQADggEBALB+CeDCm824QGL/ZU7J
2EXXSrJ1Pgmoo6QYqwGPNMQ7e8BeZiMpw0PR6d9wval19PoCywLhWIfpqjuAv5BE
zP+YDU5G6vqgWZCoYgGaN4rjP0Pnk3f1A1YRte3B73i/ldBAFRMBjEhwyNVjzLG2
h5MpCetqR1Jdcb63YtWjomiHdYagaK0KlJsjZFDfqaFZR2TGSlFPCpNULDRzwlFN
G/K2QBZN7pDqwNh+LFzQvzLdMBGlt/pz5a/0o6Wopi/e9w7XPrQoEqAhKLP5mkBL
hLAP8EOlW5g5+EemnQ9bMO3zQemT95Zge8s1YzE9kysRWue5WAH4oKUVCkCQm1x7
c1k=
-----END CERTIFICATE-----""")

x509_store = crypto.X509Store()

x509_store.add_cert(root)

try:
    x509_ctx = crypto.X509StoreContext(x509_store, cert)
    x509_ctx.verify_certificate()
except crypto.X509StoreContextError as exc:
    print('Success: verify reported "%s"' % exc.args[0][2])
else:
    print("Failure: verify didn't report an error")
```

The expected result is:

    Success: verify reported "certificate has expired"

However, with cryptography 3.1.1 and later, I instead see:

    Failure: verify didn't report an error

**Comment by ronf** [comment] 2020-11-21 05:48
Using the two certs above, I was able to reproduce this problem with a standard 'openssl' binary without Python or cryptography involved at all.

Storing the two certs above in the files "root.pem" and "cert.pem" respectively, I ran the following:

    openssl verify -CAfile root.pem cert.pem

In the case of OpenSSL 1.1.1g, I got back the expected output of:

    OU = root
    error 10 at 1 depth lookup: certificate has expired
    error cert.pem: verification failed

When running the same test against OpenSSL 1.1.1h, I instead got back:

    cert.pem: OK

So, this appears to be an OpenSSL issue.

**Comment by ronf** [comment] 2020-11-21 23:41
I haven't fully tracked down the source of the problem, but I have filed openssl/openssl#13471 about this issue. It appears to be a behavior change in OpenSSL related to verifying the root of a chain. I'm not really sure if this was an intentional change or not.

**Comment by ronf** [comment] 2020-11-22 00:43
On another note, I discovered why I didn't see this issue earlier in my macOS test. I had used the "develop" branch for that instead of 2.4.2, and I had forgotten that I had already removed the expired root CA test there.  I had run across the problem before this but didn't really have the time then to track it down, and didn't want my unit tests to fail in the meantime. Since I had other tests which already covered all the relevant code paths in AsyncSSH, I thought it was easiest to just remove it.

Once I see what the OpenSSL devs have to say on this, I'll figure out whether or not there's a way to add this test back in, though it'd have to be conditional on the OpenSSL version which is used.

**Comment by gsauthof** [comment] 2020-11-22 20:50
Thank you for taking care of this issue.

**Comment by ronf** [comment] 2020-12-23 19:06
The fix for this was merged into OpenSSL a few weeks ago and appears to be part of the 1.1.1i release. I just confirmed here that OpenSSL is once again properly reporting expiration of a root certificate during verification. Given the version dependency, though, I think I will leave this out of the AsyncSSH unit tests for now, since it is not required to to get full coverage of AsyncSSH itself.

**Closed by ronf** 2020-12-23 19:06 UTC
